### ISSUE TITLE
[Android Chrome - QR Code] Can't scan QR code when in dark mode

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#1000]
Phone is able to scan QR code when in Light mode, but not in Dark mode.
![photo_2020-04-29_16-57-07](https://user-images.githubusercontent.com/51191261/80578104-932a9880-8a3a-11ea-85de-cb9341b23fe2.jpg)

**Comment by lionellbriones** [comment]
![Screen Shot 2020-04-30 at 5 30 31 PM](https://user-images.githubusercontent.com/4738957/80695319-52995080-8b08-11ea-876d-bb113fda3ede.png)
i'll use the light mode QR for now.. i'll work on it later

**Comment by itsinz** [comment]
QR Code in dark mode still does not work.

**Comment by chaitanyapotti** [comment]
It works if you increase screen brightness. Same issue with movie theater QR codes.!
