### ISSUE TITLE
[Android Chrome - Top-up] Xanpool Topup Language Issue

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#1001]
![photo_2020-04-29_17-16-37](https://user-images.githubusercontent.com/51191261/80579841-41374200-8a3d-11ea-8cce-3456980403a2.jpg)
Android Chrome opens Xanpool top-up in Chinese. (Torus app language is set as English)

**Comment by chaitanyapotti** [comment]
Not an issue with us. I'll bring this up with xanpool.
