### ISSUE TITLE
[Android Chrome - Transfer] Contact Drop-down Blocks the Fills

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#1004]
The Contact Drop-down shows automatically upon clicking the fill 'Transfer to' and it blocks 
 the fill entirely
- works well if trying to transfer to a contact that has been saved but a hassle to transfer to a new contact as you need to find the fill in order to paste a new contact 

Before:
![photo_2020-04-29_17-53-34](https://user-images.githubusercontent.com/51191261/80583115-624e6180-8a42-11ea-9507-4d24a076dcc1.jpg)

After clicking:
![photo_2020-04-29_17-53-40](https://user-images.githubusercontent.com/51191261/80583487-d6890500-8a42-11ea-8606-a3c4cab9e8a7.jpg)

**Comment by lionellbriones** [comment]
![Screenshot_20200430-080831](https://user-images.githubusercontent.com/4738957/80658873-ec85dc80-8ab9-11ea-9a59-f6b843cedf29.png)
this is because the keyboard is blocking the screen, when you start typing, it will highlight the characters on the list available

**Comment by chaitanyapotti** [comment]
Acceptable behaviour
