### ISSUE TITLE
[Transfers] Unable to send ETH in USD value

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#1006]
After changing currency to USD --> Transfer --> Balance value (number) remains in ETH but the currency is in USD 
- Typing amount to be transferred: Although the currency is in USD, value is calculated as ETH

![photo_2020-04-29_18-14-40](https://user-images.githubusercontent.com/51191261/80585133-629c2c00-8a45-11ea-8639-7acfa1700c8d.jpg)

When trying to change the currency to ETH:
![doc_2020-04-29_18-15-56 2020-04-29 18_17_03](https://user-images.githubusercontent.com/51191261/80585393-d6d6cf80-8a45-11ea-8015-62ac058ad391.gif)

**Comment by rathishubham7** [comment]
There's an issue with the balance display across the application. Balance dropdown doesn't add the value of ERC20 tokens.

**Comment by rathishubham7** [comment]
<img width="1002" alt="Screenshot 2020-04-29 at 7 30 43 PM" src="https://user-images.githubusercontent.com/16849485/80591409-3b972780-8a50-11ea-9323-6c8be08af4ad.png">

**Comment by rathishubham7** [comment]
<img width="1087" alt="Screenshot 2020-04-29 at 7 30 46 PM" src="https://user-images.githubusercontent.com/16849485/80591438-48b41680-8a50-11ea-8402-eda514c3d73e.png">
