### ISSUE TITLE
[Transfer ERC20] Values and currencies stated are swapped

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#1008]
1) The amount shown is in KNC but currency says it's ETH
![image](https://user-images.githubusercontent.com/51191261/80586350-6761df80-8a47-11ea-8af9-1096d0188a7a.png)

**Comment by itsinz** [comment]
This is un-intended. This issue will be addressed by resolving #1009

**Comment by chaitanyapotti** [comment]
Closing this in reference to #1009
