### ISSUE TITLE
[Transfer] Currency switch is quite counterintuitive 

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#1009]
I would expect to click on 'KNC' in order to switch to KNC since it is 'unhighlighted' 
But currently, you have to click on the already highlighted 'ETH' to switch to KNC

![photo_2020-04-29_18-34-49](https://user-images.githubusercontent.com/51191261/80586899-41890a80-8a48-11ea-9a0d-c4a9bb780b32.jpg)

**Comment by rathishubham7** [comment]
Refer to designs

**Comment by itsinz** [comment]
<img width="706" alt="Screenshot 2020-04-30 at 8 50 33 AM" src="https://user-images.githubusercontent.com/53069682/80660921-b9dee280-8abf-11ea-8351-c554673af38d.png">
To amend UI to new proposed one as above
