### ISSUE TITLE
[Import Account] Account information of newly imported account is different 

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#1010]
Details of the imported account duplicates the host account (only the public addresses differ)

![image](https://user-images.githubusercontent.com/51191261/80589893-97ac7c80-8a4d-11ea-9873-349b4fc3551c.png)
![image](https://user-images.githubusercontent.com/51191261/80590020-caef0b80-8a4d-11ea-9183-86d183072ed5.png)

**Comment by rathishubham7** [comment]
The block for import account is placed in wrong container.

**Comment by itsinz** [comment]
> The block for import account is placed in wrong container.

<img width="253" alt="Screenshot 2020-04-30 at 1 46 02 PM" src="https://user-images.githubusercontent.com/53069682/80676326-19051d00-8ae9-11ea-81f0-ba2a82c7fd8b.png">
this would be the 'containers'

Key function of "Transfer", "Top-up", "Settings", "Activity" will be together, separate from the rest on mobile. To indicate they belong to key functions while the others are supplementary functions.

Discussed with Lionell on this already. He's on it now. All good.
