### ISSUE TITLE
[Safari-Desktop Account] Make Twitch Account icon dark mode to be grey

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1015]
Currently there is purple in the twitch icon in dark mode
Kindly use the grey twitch darkmode <img width="402" alt="Screenshot 2020-04-30 at 9 17 45 AM" src="https://user-images.githubusercontent.com/53069682/80662573-2f4cb200-8ac4-11ea-98a7-7040e93c6cc8.png">
(Existing purple in dark mode)
<img width="108" alt="Screenshot 2020-04-30 at 9 23 51 AM" src="https://user-images.githubusercontent.com/53069682/80662640-57d4ac00-8ac4-11ea-9190-4663c6009f8d.png">
(please use grey dark mode just like in contact list)

**Comment by lionellbriones** [comment]
icon already the same with contact list
