### ISSUE TITLE
[Safari-Desktop Topup] Xanpool top up min is 0.1 ETH, not 1 USD

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1017]
To amend copywriting in Xanpool top up in Torus Wallet. To be 0.1 ETH rather than 1 USD
<img width="417" alt="Screenshot 2020-04-30 at 9 35 21 AM" src="https://user-images.githubusercontent.com/53069682/80663253-09c0a800-8ac6-11ea-971c-c77e8b297014.png">
<img width="611" alt="Screenshot 2020-04-30 at 9 32 24 AM" src="https://user-images.githubusercontent.com/53069682/80663255-0c230200-8ac6-11ea-94e8-a29feef10080.png">

**Comment by chaitanyapotti** [comment]
Fixed

**Comment by itsinz** [comment]
To amend the amount to be 30 SGD instead of 1 SGD.
Since it is 0.1 ETH = approx 30 SGD now. 

<img width="659" alt="Screenshot 2020-05-01 at 4 24 39 PM" src="https://user-images.githubusercontent.com/53069682/80793006-72904900-8bc8-11ea-98f3-1a1e017dcbd6.png">

**Comment by chaitanyapotti** [comment]
Made min to be 30
