### ISSUE TITLE
Wrong Balance within Transfer Page

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#1024]
**Describe the bug**
The balance shown within the Transfer page does not coincide with the balance shown on the home page.

**To Reproduce**
1. Go to Transfer Page
2. See the wrong balance

**Expected behavior**
The balance of ETH should be the same, even in USD as the balance shown in the Home Page.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
- Browser: Chrome
![Screenshot 2020-04-30 at 5 05 10 PM](https://user-images.githubusercontent.com/51352241/80693027-01d42880-8b05-11ea-9b25-51140acb78f1.png)
![Screenshot 2020-04-30 at 5 00 59 PM](https://user-images.githubusercontent.com/51352241/80693034-03055580-8b05-11ea-845f-287e1cd71995.png)

**Comment by itsinz** [comment]
i still get this wrong balance issue.

**Comment by itsinz** [comment]
<img width="1437" alt="Screenshot 2020-05-01 at 4 57 29 PM" src="https://user-images.githubusercontent.com/53069682/80794626-f5b39e00-8bcc-11ea-8d1d-800232429c10.png">
Completely wrong account total value shown.
Supposed to have 122 USD in account.

**Comment by chaitanyapotti** [comment]
the rates API failed in this request and hence the balance is like that.
Pls reload. We are in discussion with coingecko to improve the reliability of their API

**Comment by chaitanyapotti** [comment]
Seems to be an API issue with coingecko. It's not always there. We have a call scheduled with them for queries related to performance.
