### ISSUE TITLE
Insufficient Balance shown in the Transfer Page

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#1026]
**Describe the bug**
When trying to do a Transfer, insufficient balance is shown despite having more than enough balance on the home page.

**To Reproduce**
1. Go to Transfer Page
2. Enter the amount to transfer within the balance amounts.

**Expected behavior**
The balance should be the same as in the home page.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
![Screenshot 2020-04-30 at 5 01 12 PM](https://user-images.githubusercontent.com/51352241/80693623-e289cb00-8b05-11ea-95f1-5baa98dcf818.png)
![Screenshot 2020-04-30 at 5 05 10 PM](https://user-images.githubusercontent.com/51352241/80693627-e3baf800-8b05-11ea-85f8-00c617520139.png)

**Comment by chaitanyapotti** [comment]
ETH is selected there... you were trying to transfer 1 ETH and hence, it showed so.

@itsinz as discussed, this is not intuitive about which is selected.
