### ISSUE TITLE
Icon for Dark mode can be improved for visibility

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#1027]
**Describe the bug**
The bicycle and motor-vehicle icon within the transfer page between transfer speeds can be improved for visibility.

![Screenshot 2020-04-30 at 11 52 40 AM](https://user-images.githubusercontent.com/51352241/80693759-15cc5a00-8b06-11ea-940c-a0cc02d6eefd.png)

**Comment by itsinz** [comment]
<img width="622" alt="Screenshot 2020-04-30 at 5 17 57 PM" src="https://user-images.githubusercontent.com/53069682/80694060-8e331b00-8b06-11ea-9b22-90e773cda68d.png">
Please find dark mode under vue-embed on figma
