### ISSUE TITLE
[Transfer] Transaction is "Receive from Sender" but shown as "Sent to Recipient"

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1031]
**Describe the bug**
I sent 1 USD from account A to the account B.
When I login to account B, proceed to activity page, it says my account B account SENT 1 USD to account B. This is incorrect.

**To Reproduce**
1. Send 1 USD from account A to account B
2. Login to Account B, go to activity
3. It shows 1 USD SENT fro Account B to Account B (this is incorrect)

**Expected behavior**
It is supposed to be
Received ETH
from: (Address of Account A)

Right now it is
Sent ETH
to: (Address of Account B)

Please refer to transaction hash : https://etherscan.io/tx/0x760d4f9627772d57b6461f3dcfe1a0751c851b8b331e91da24ef85ab1d443184

**Screenshots**
<img width="1173" alt="Screenshot 2020-04-30 at 6 23 51 PM" src="https://user-images.githubusercontent.com/53069682/80700499-6ba5ff80-8b10-11ea-8f30-f5b19f71c571.png">

**Desktop (please complete the following information):**
 - Safari

**Comment by chaitanyapotti** [comment]
Not an issue
