### ISSUE TITLE
[iOS-Chrome Login] Unable to scroll down

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1037]
At login page for mobile iOS chrome, 

unable to scroll down to view the additional content (the content on the right side of the desktop screen)
Instead, after 7 seconds, will be directed to the additional content (the content on right side of the desktop screen)
![image](https://user-images.githubusercontent.com/53069682/80779205-7fe40e00-8b9d-11ea-904c-a7e3f47c32f9.png)

**Comment by lionellbriones** [comment]
I fixed the second issue.. The first one will take time
