### ISSUE TITLE
[iOS Chrome - Transfer] Incorrect selected and unselected currency

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1041]
Current when USD is selected: 
![image](https://user-images.githubusercontent.com/53069682/80786825-546e1d00-8bb7-11ea-9774-632040bc2b7b.png)

Proposed when USD is selected please **bold** the selected and make it bright, exact specs on figma:
<img width="346" alt="Screenshot 2020-05-01 at 2 15 32 PM" src="https://user-images.githubusercontent.com/53069682/80786527-8632b400-8bb6-11ea-8e6f-98b021f70624.png">

**Comment by chaitanyapotti** [comment]
This is in contradiction to other buttons on the website which upon pressed state, go dark.
Please address this

**Comment by itsinz** [comment]
> This is in contradiction to other buttons on the website which upon pressed state, go dark.
> Please address this

To amend Theme change, and currency according to new UI
ie, both same card, selected option will have **bold** text and unselected option will be in regular text, at 30% opacity
<img width="421" alt="Screenshot 2020-05-01 at 3 10 48 PM" src="https://user-images.githubusercontent.com/53069682/80789295-2809cf00-8bbe-11ea-8886-0ad4eb844de6.png">

<img width="433" alt="Screenshot 2020-05-01 at 3 10 53 PM" src="https://user-images.githubusercontent.com/53069682/80789291-250ede80-8bbe-11ea-9b76-4373694024b1.png">
