### ISSUE TITLE
[iOS Chrome- Transfer] Hard refresh required to update collectibles page otherwise a sent collectible is still shown

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1045]
Situation:
Sent an ERC721, activity page said the transaction was successful.
Went back to homepage, that particular ERC 721 still shown in collectible section.
Had to manually refresh for it to be gone.
Kindly verify if auto refresh is possible or we need that refresh button?
![image](https://user-images.githubusercontent.com/53069682/80789717-65229100-8bbf-11ea-85da-b87312eb07fa.png)

**Comment by chaitanyapotti** [comment]
Auto refresh happens every minute. Please be a little bit more patient :smile:

**Comment by itsinz** [comment]
cannot la
