### ISSUE TITLE
[iOS Chrome - Transfer Email] Transfer KNC but shown ETH

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1049]
Transferred KNC but shown ETH.
Any way to update tokens icon?
![image](https://user-images.githubusercontent.com/53069682/80790874-96509080-8bc2-11ea-8818-f20ac588b242.png)

**Comment by chaitanyapotti** [comment]
we decided that if we don't have png/jpg of icon, we would show eth symbol.!

**Comment by itsinz** [comment]
but we do have KNC right or is it because KNC icon is in svg? else how did we show KNC in wallet?
