### ISSUE TITLE
[Brave - Export Key] Unable to export key, stuck at encrypting

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1051]
Unable to export discord acc key, stuck at encrypting
<img width="1440" alt="Screenshot 2020-05-01 at 4 52 01 PM" src="https://user-images.githubusercontent.com/53069682/80794325-3ced5f00-8bcc-11ea-82b6-469e9be956cc.png">

**Comment by chaitanyapotti** [comment]
Not an issue
