### ISSUE TITLE
Transfer Total Cost Not Updated

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#1052]
**Describe the bug**
After entering an amount to send, and toggling between ETH and USD, the total cost of the transaction does not update to accurately reflect the total cost of the transaction, and still shows a 0.

**To Reproduce**
1. Go to Transfer Page.
2. Enter the amount.
3. Toggle between USD and ETH.

**Expected behavior**
The total amount of the transaction should be updated, also, the indicators aren't clear between ETH and USD in Dark Mode.

**Screenshots**
![Screenshot 2020-05-01 at 5 26 31 PM](https://user-images.githubusercontent.com/51352241/80796440-bfc4e880-8bd1-11ea-94a5-23d0a6025468.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - OS: Chrome

**Comment by chaitanyapotti** [comment]
toggle out of the field for it to update
