### ISSUE TITLE
Balance is wrong in Startrail widget 

### ISSUE THREAD

**Issue by carloslastresDev** [torusresearch/torus-website#1079]
**Describe the bug**
The balance displayed on widget is wrong

**To Reproduce**
1. Go to https://vue-embed.tor.us/
2. Click on login with Google
3. Open Widget

**Expected behavior**
Same balance as the one in your app

**Screenshots**
![image](https://user-images.githubusercontent.com/15041375/81539388-bcd0b180-93a2-11ea-9bac-2aa62ce40743.png)
but I actually have
![image](https://user-images.githubusercontent.com/15041375/81539416-c6f2b000-93a2-11ea-97b3-019960b166b4.png)

**Desktop (please complete the following information):**
 - Chrome MacOS

**Comment by carloslastresDev** [comment]
The balance problem is the network. Startrail is loading another network but you are never being informed

**Comment by chaitanyapotti** [comment]
My example dapp loads on rinkeby by default. This is intended for testing purposes
