### ISSUE TITLE
Every time I click the widget, the screen goes with background blur but also the pop-up to login appears

### ISSUE THREAD

**Issue by carloslastresDev** [torusresearch/torus-website#1080]
**Describe the bug**

**To Reproduce**
1. Go to https://vue-embed.tor.us/
2. Click on login with google
3. Click the widget more than 2 times. Login pop-up appears

**Expected behavior**
No pop-up

**Screenshots**

![image](https://user-images.githubusercontent.com/15041375/81540417-387f2e00-93a4-11ea-9007-3a121b47cc0a.png)

**Desktop (please complete the following information):**
 - Chrome MacOS

**Comment by chaitanyapotti** [comment]
Fixed
