### ISSUE TITLE
[Dark mode] Unable to change to dark mode when whitelabel is active

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1083]
<img width="1440" alt="Screenshot 2020-05-11 at 4 57 12 PM" src="https://user-images.githubusercontent.com/53069682/81543525-c2c99100-93a8-11ea-9cbe-5227b70f4334.png">

Click on the dark mode in wallet and unable to change to dark mode.

**Comment by chaitanyapotti** [comment]
The discussion needs to be like:
If a company specifically requested light mode, should we allow users to switch to dark mode or not?

**Comment by chaitanyapotti** [comment]
Business decision: Intended
