### ISSUE TITLE
[QR Code] Does not work on mobile and desktop

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1125]
<img width="1440" alt="Screenshot 2020-06-01 at 2 23 19 PM" src="https://user-images.githubusercontent.com/53069682/83381535-80c5c500-a413-11ea-86f3-4b534f939893.png">
<img width="513" alt="Screenshot 2020-06-01 at 2 27 38 PM" src="https://user-images.githubusercontent.com/53069682/83381760-16f9eb00-a414-11ea-8f8d-2ac0ff4d33ab.png">

Both mobile and desktop, dark and light mode, QR code does not show

**Comment by chaitanyapotti** [comment]
Already fixed on testing
