### ISSUE TITLE
[Chrome Mac] Unable to Log in using Twitch

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#1126]
![image](https://user-images.githubusercontent.com/51191261/83478011-4f0e3600-a4c7-11ea-91f1-0e146e1d0870.png)
I am continuously faced with this error... 
Have tried clearing my cookies and cache but I am still stuck with this. 
It works perfectly in incognito as well as my phone though.

**Comment by chaitanyapotti** [comment]
Seems to be an issue with twitch
