### ISSUE TITLE
Wrong badge after login into existing account

### ISSUE THREAD

**Issue by carloslastresDev** [torusresearch/torus-website#1127]
Using my Reddit account I logged in to the app. This is an existing account but only used for testing purposes. Once I got in, shows me "transaction badge". I don't remember the last time I used this wallet so for this type of wallets, is better just show the badge colored instead of the pop-up at login, otherwise feels weird why I have a transaction when I just logged in

**To Reproduce**
1. Go to https://testing.tor.us/
2. Use any account with a tx

**Expected behavior**
Just the badge colored if you have done transactions 

**Screenshots**

![image](https://user-images.githubusercontent.com/15041375/83485979-c600fa00-a4da-11ea-8b6c-721b2948e92f.png)

**Desktop (please complete the following information):**
 - OS Macbook, Chrome

**Comment by itsinz** [comment]
I get all badges during first login.
1. Top up
2. Transact
3. Collectibles

Badges should only be triggered when an action is carried out (eg top up / transact)

<img width="1440" alt="Screenshot 2020-06-02 at 2 18 09 PM" src="https://user-images.githubusercontent.com/53069682/83486791-74596f00-a4dc-11ea-8da5-a5b09bed803d.png">

**Comment by chaitanyapotti** [comment]
Badges removed for now
