### ISSUE TITLE
[Account] There are 3 accounts when i log in

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1129]
When I login to iOS Chrome, there are 3 accounts under my account. I did not import any account on testing.

Supposed to be just 1 account

Replicate : Login to testing.tor.us on mobile, go account, there are 3 accounts in the drop down
![photo_2020-06-02_17-59-40](https://user-images.githubusercontent.com/53069682/83507329-ffe1f880-a4fa-11ea-935b-9f0f58ab217c.jpg)

**Comment by chaitanyapotti** [comment]
Not a bug
