### ISSUE TITLE
Version the built embed.min.js artifact using commit hash during CI build

### ISSUE THREAD

**Issue by opaolini** [torusresearch/torus-website#113]
Background
===

We should version the embeddable script artefact using the `COMMIT_HASH` of the current branch, like so:
```
embed.<COMMIT_HASH[0:7]>.min.js
```

Which, for the current develop branch (commit `2647988f4f95cde1e12e60cc2f9172062e13cabc`) would make the snippet on https://tor.us look like so:
```
<script src="https://tor.us/embed.2647988.min.js" integrity="sha384-qK/ezXS8qjCsKwF/VCLpjwCsFprUnJLz7455WV3gRRaldDufLq1bkjEpiAikSOVK" crossorigin="anonymous"></script>
```

This gives us some benefits:
- We get versioning out of the box, and if someone will have issues we will know exactly which commited version that is.
- We won't break the already deployed versions (failed integrity check) upon releasing a new one.
- We will save on cache invalidations on CDNs

**Comment by chaitanyapotti** [comment]
Finally implemented this but in a different way
Since, we have urls like https://app.tor.us/v0.0.15/embed.min.js
versioning is built into the requested url
