### ISSUE TITLE
Font on mobile is different, please change back to Roboto

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1130]
Font on testing.tor.us on mobile iOS chrome is diff from on app.tor.us on mobile iOS chrome. The one on testing.tor.us is not legible, too thin. Make it the same as on app.tor.us (last image)

On testing.tor.us
![photo_2020-06-02_18-08-23](https://user-images.githubusercontent.com/53069682/83508271-4126d800-a4fc-11ea-932b-5f55df57c490.jpg)
![photo_2020-06-02_18-08-19](https://user-images.githubusercontent.com/53069682/83508276-4421c880-a4fc-11ea-8300-0fb34428afdb.jpg)

on app.tor.us (this is how it is supposed to look like)
![photo_2020-06-02_18-09-57](https://user-images.githubusercontent.com/53069682/83508321-556ad500-a4fc-11ea-9131-a2b25572be83.jpg)

**Comment by chaitanyapotti** [comment]
Looks like the font file failed loading that time.! Pls let me know if it's recurring
