### ISSUE TITLE
[Torus Widget] Display of NaN ETH 

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1155]
Incorrect display of latest transaction on Torus Widget
When you login and click on the widget, the lastest transaction is displayed as "NaN ETH" and it says "Send ETH in Japanese"
however, when you go to your wallet activity page, the latest transaction is actually "Receive ETH" on my wallet

Widget
<img width="335" alt="Screenshot 2020-06-23 at 6 05 12 PM" src="https://user-images.githubusercontent.com/53069682/85392629-60a2a500-b57e-11ea-93eb-d46062f75bae.png">

Wallet
<img width="914" alt="Screenshot 2020-06-23 at 6 23 17 PM" src="https://user-images.githubusercontent.com/53069682/85392937-cd1da400-b57e-11ea-8a10-0ae03357192d.png">

- Chrome on MacOS

**Comment by rathishubham7** [comment]
was this a transaction sent to self ?

**Comment by rathishubham7** [comment]
resolved
