### ISSUE TITLE
[Sign typed data 1, 3, 4] Flicker language from Jap - Eng - Jap

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1159]
Sign typed data 1, 3, 4 language will dance from Jap, to Eng, then back to Jap
<img width="504" alt="Screenshot 2020-06-23 at 6 38 36 PM" src="https://user-images.githubusercontent.com/53069682/85394556-559d4400-b581-11ea-9b7f-c1feac924836.png">
<img width="497" alt="Screenshot 2020-06-23 at 6 37 58 PM" src="https://user-images.githubusercontent.com/53069682/85394568-5930cb00-b581-11ea-94bd-525824ba6323.png">

**Comment by carloslastresDev** [comment]
Happens also in Brave/Firefox

**Comment by chaitanyapotti** [comment]
Fixed
