### ISSUE TITLE
Email password on vue embed does not work

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1160]
- Chrome, MacOS
Emaill password on vue embed does not work.
Click on sign in with email password and was shown this error page
<img width="1440" alt="Screenshot 2020-06-23 at 6 46 42 PM" src="https://user-images.githubusercontent.com/53069682/85395115-39e66d80-b582-11ea-9dc2-48d607173639.png">

**Comment by chaitanyapotti** [comment]
A required parameter was not specified in the example which caused this issue. It's fixed now.
Startrail Login will only work in LRC env
