### ISSUE TITLE
To update latest Torus logo for Facebook and Discord

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1162]
To update latest Torus Logo (the darker blue) for Faceboook an Discord logins.
<img width="524" alt="Screenshot 2020-06-23 at 7 36 49 PM" src="https://user-images.githubusercontent.com/53069682/85402466-512b5800-b58e-11ea-8982-d1ce7c7f289f.png">

**Comment by chaitanyapotti** [comment]
Done
