### ISSUE TITLE
[Android Chrome] Unable to log in with Discord

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#1164]
Upon logging onto Discord, you are prompted with which app you would like to open with (similar results for all), and before that pops up, you actually see an error message which gets blocked by the "open with" pop up.

After authentication, the screen shows the loading screen (which takes rather long ~5 secs)
and then the screen asking you to close the window. 
After closing the window to return to the wallet, it remains at the login screen

<img width="425" alt="Screenshot 2020-06-24 at 4 05 23 PM" src="https://user-images.githubusercontent.com/51191261/85519744-868a8100-b634-11ea-8b9a-9d82dbecdea9.png">

![Discord Login](https://user-images.githubusercontent.com/51191261/85519644-6490fe80-b634-11ea-87de-08b766149816.png)

**Comment by hagiosssss** [comment]
Same issue occurs for Github login as well

**Comment by chaitanyapotti** [comment]
Fixed
