### ISSUE TITLE
[Imported acc] Icon and account info is not shown

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1166]
When I import my reddit account
(i) the imported account logo is not reddit
(ii) the reddit user is not shown on the imported act, just the address. (not sure if it is intended this way)

To make imported acc reflect the respective oauth logo.

![photo_2020-06-24_17-02-24](https://user-images.githubusercontent.com/53069682/85526435-96a65e80-b63c-11ea-8f2a-3a6fff2baaf5.jpg)

**Comment by chaitanyapotti** [comment]
Duplicate issue. We have no way to identify the account belongs to a reddit wallet. So, we just show it as an imported account.
