### ISSUE TITLE
[Mobile Account] To allow scrolling on account dropdown on mobile otherwise user cannot log out

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1167]
When i import an account on mobile, the account dropdown will exceed phone screen (as shown below) and I am unable to scrolling to the bottom. Hence, unable to log out of my account, unless I exit the site.

Is it possible to make the account dropdown scrollable so user can click on the "Log out" function if dropdown size exceeds the mobile screen size?

![photo_2020-06-24_17-09-34](https://user-images.githubusercontent.com/53069682/85527493-80e56900-b63d-11ea-93d6-2711a3a1a253.jpg)

**Comment by lionellbriones** [comment]
Fixed
