### ISSUE TITLE
Improve UI of login with terms

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1185]
To improve ui (the note section, below all the icons) of login page in web and modal.

Current version
<img width="1440" alt="Screenshot 2020-07-05 at 12 01 20 AM" src="https://user-images.githubusercontent.com/53069682/86516548-19f15c80-be54-11ea-93e4-6803190443fb.png">
.
.

Proposed Version
<img width="350" alt="Screenshot 2020-07-05 at 3 19 57 PM" src="https://user-images.githubusercontent.com/53069682/86527608-37b1d680-bed3-11ea-840a-ab0294725320.png">
<img width="842" alt="Screenshot 2020-07-05 at 3 19 36 PM" src="https://user-images.githubusercontent.com/53069682/86527609-3bddf400-bed3-11ea-8f47-b4dba62e161d.png">

.
.
.
The copywriting have been updated with translation onto airtable. Respective hyperlink can be found in Figma, super login, 
extreme right

To include in code the following:
dappLogin.note
dappLogin.termsAuth01
dappLogin.termsAuth02
dappLogin.termsLearnMore
dappLogin.termsHandle
dappLogin.termsConditions
dappLogin.privacyPolicy
dappLogin.contactUs

**Comment by carloslastresDev** [comment]
Totally approved. Let's try to make the rows to have the same amount of logins
