### ISSUE TITLE
Unable to transfer via Twitter handle

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1186]
Tried on both Chrome and Edge, unable to transfer to Twitter handle
Tried "pooyootoo" but field text says Invalid Twitter Username
<img width="1440" alt="Screenshot 2020-07-05 at 1 08 54 AM" src="https://user-images.githubusercontent.com/53069682/86517529-3b564680-be5c-11ea-8df5-c57333bde73e.png">

**Comment by itsinz** [comment]
need to include '@' to transfer via twitter.

Option 1
Please add additional error message type:
Error: Twitter handle begins with "@"

Option 2
auto refill '@' for users when they select "Twitter username"

Question, is twitter handle case sensitive?

**Comment by chaitanyapotti** [comment]
Not case sensitive. I'm using option 1
