### ISSUE TITLE
Unable to login via vue-embed on Firefox

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1187]
Trying to login to vue embed on firefox but does not work
<img width="1440" alt="Screenshot 2020-07-05 at 1 37 02 AM" src="https://user-images.githubusercontent.com/53069682/86517998-211e6780-be60-11ea-8def-8bd6dcbc8bcf.png">

**Comment by tetratorus** [comment]
Referrer-Policy on vue-embed.tor.us was set to "same-origin". We rely on document.referrer in browser that don't support window.location.ancestorOrigins (i.e. Firefox/IE), and document.referrer is not passed if you have a restrictive Referrer-Policy.

For now, the solution is to set the parent site's Referrer-Policy to something less restrictive.
