### ISSUE TITLE
Incorrect transaction History displayed

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1188]
Situation:
- Login to twitter acc
- Imported account A
- select account A
- transfer from account A to twitter 
- log out of twitter acc
- login to twitter acc again
- transaction stated "SENT ETH, EXTERNAL TX"
it is supposed to be Received ETH. without external tx label.

<img width="1440" alt="Screenshot 2020-07-05 at 1 47 29 AM" src="https://user-images.githubusercontent.com/53069682/86518188-fa613080-be61-11ea-804c-e661d7a3373b.png">

**Comment by chaitanyapotti** [comment]
Fixed this to say Received ETH but transactions made from imported accounts are not stored. So, we will still show it as an external transaction
