### ISSUE TITLE
Adding loader gif to places where users are supposed to wait

### ISSUE THREAD

**Issue by tetratorus** [torusresearch/torus-website#130]
We should add loading indicators (https://loading.io/?) to the following:

transactions
loggin in

**Comment by chaitanyapotti** [comment]
I don't think it is an issue anymore. Please test staging.tor.us and let me know if the window isn't instantaneous. 
If not, Let's use [Vuetify Loaders](https://vuetifyjs.com/en/components/progress) since we are already packaging that library
