### ISSUE TITLE
testing.tor.us - Unable to locate bank statement 6 digit code for wyre top up

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1309]
Unable to locate 6 digit code for wyre top up
I only managed to find 4 digit code but unable to proceed
![image](https://user-images.githubusercontent.com/53069682/99043404-2a1b0480-25c9-11eb-8066-45124b80e4fc.png)
<img width="1440" alt="Screenshot 2020-11-13 at 3 57 55 PM" src="https://user-images.githubusercontent.com/53069682/99043407-2c7d5e80-25c9-11eb-8a33-256a7943a489.png">

**Comment by chaitanyapotti** [comment]
This is only for USA banks
