### ISSUE TITLE
Website not working in MEW

### ISSUE THREAD

**Issue by chaitanyapotti** [torusresearch/torus-website#131]
![image](https://user-images.githubusercontent.com/1688380/54510565-e6937180-4973-11e9-9e0e-f81112060d63.png)

The CSP is defined by myetherwallet.com and not our script. It works perfectly in etheremon.com and cryptokitties

**Comment by tetratorus** [comment]
you cant use it in mew because of this, the version I have on https://github.com/torusresearch/test-mew removes this content security policy header
