### ISSUE TITLE
On receipt of successful tx, activity page shows unsuccessful

### ISSUE THREAD

**Issue by YZhenY** [torusresearch/torus-website#1317]
this occurs for both tkey and non tkey accounts

**To Reproduce**
1. send eth to account

**Screenshots**

![image](https://user-images.githubusercontent.com/25172440/99877738-393e2a00-2c3b-11eb-8c01-efe4bef8370e.png)

![image](https://user-images.githubusercontent.com/25172440/99877777-71456d00-2c3b-11eb-9eea-8790df038576.png)

**Smartphone (please complete the following information):**
 - Device: iphone 11 pro
 - OS: ios
 - Browser  safari

**Comment by chaitanyapotti** [comment]
Unable to repro
