### ISSUE TITLE
On requiring share transfer, if a request pops up on an app and request is fufilled in some other way. UX is bad.

### ISSUE THREAD

**Issue by YZhenY** [torusresearch/torus-website#1320]
On requiring share transfer, if a request pops up on an app and request is fufilled in some other way it just stalls, when you click confirm nothing happens. Lets handle it in a way where we return an error or say the request has been already fufilled/rejected
![image](https://user-images.githubusercontent.com/25172440/99897853-f8e0b980-2cd7-11eb-9a6b-bb5f7695f423.png)

**Comment by chaitanyapotti** [comment]
Fixed already
