### ISSUE TITLE
[Function] On uniswap, wallet switch does not work

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1321]
Situation
on iOS Safari, connect to uniswap with Torus wallet.
Q1. there was no login pop up, instantly signed in to my tKey account. Is this because a share was detected?
Default tKey was shown.
Click on Torus widget
Click open wallet
Click account dropdown
Select email account
Close account drop down
return to uniswap, 
Q2. Account connected is still tKey account. Is this because tKey is set as default?
If so, 
I went to Torus wallet
Switch default account to email account in settings
return to Uniswap
Q3. tKey wallet is still the one connected. It should be changed to email account

Goal: To allow users to switch between accounts conveniently when transacting on Dapp.
Ideal flow: Example, if user set tkey as default, they can still switch to email account in account drop down, and access their email account and transact with it on uniswap.

**Comment by chaitanyapotti** [comment]
You need to disconnect and connect again in uniswap.
