### ISSUE TITLE
[Function] Unable to select token to swap on uniswap

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1322]
For both iOS Chrome and Safari, unable to detect token to swap
![photo_2020-11-22_16-21-21](https://user-images.githubusercontent.com/53069682/99898749-e322c280-2cde-11eb-8267-04788b46377e.jpg)

**Comment by chaitanyapotti** [comment]
Bug in uniswap. 
Uniswap token list default selection may fail sometimes.
You need to click on 'select a list' at the bottom then.!
