### ISSUE TITLE
[Function] Firefox - unable to login to uniswap.tor.us

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1324]
Unable to login to uniswap.tor.us on firefox
<img width="1440" alt="Screenshot 2020-11-22 at 4 53 13 PM" src="https://user-images.githubusercontent.com/53069682/99899307-457dc200-2ce3-11eb-8f8d-4c15bd8c5f90.png">

**Comment by chaitanyapotti** [comment]
Fixed. This is due to referrer policy header
