### ISSUE TITLE
[UI] Add vertical margin for text in Transfer screen 

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1338]
Ensure handle and address does not overlap on transfer screen
<img width="419" alt="Screenshot 2020-11-23 at 5 28 01 PM" src="https://user-images.githubusercontent.com/53069682/99946541-7b897780-2db1-11eb-9ee3-c3f620b0a4ee.png">

**Comment by chaitanyapotti** [comment]
Fixed
