### ISSUE TITLE
Incorrect assets value display after network change

### ISSUE THREAD

**Issue by Iamshashvat** [torusresearch/torus-website#1339]
**Describe the bug**
After changing the network and coming back on home page account balance display incorrect assets value 

**To Reproduce**
1. Go to Setting
2. Change the network 
3. Go back to home
4. See incorrect value

**Expected behavior**
It should show my actual asset value.
**Screenshots**
![image](https://user-images.githubusercontent.com/21297284/99953069-b1752e80-2da6-11eb-9683-71b92227749a.png)
Incorrect Value
After refresh it show me correct value.
**Desktop**
 - Browser chrome
 - Version 86.0.4240.198 (Official Build) (64-bit)

**Additional context**
This issue is not frequent sometimes it shows correct value.

**Comment by chaitanyapotti** [comment]
We've already identified this.
This will be fixed in the latest release.! v1.9.0
