### ISSUE TITLE
Changing selected address on torus wallet doesn't reflect on dApp

### ISSUE THREAD

**Issue by lionellbriones** [torusresearch/torus-website#1340]
**Describe the bug**
I changed the selected address on torus wallet but it did not reflect on dApp (https://uniswap.tor.us)

**To Reproduce**
1. Go to [https://uniswap.tor.us/#/swap](url)
2. Connect using Torus (used account with tKey as default)
3. Open Wallet through the torus widget and change selected wallet on account menu
4. Go back to dApp
5. Selected address is updated on the Torus widget but not on dApp

**Expected behavior**
dApp should use the selected wallet

**Screenshots**
![Screen Shot 2020-11-24 at 4 07 24 PM](https://user-images.githubusercontent.com/4738957/100066408-06c94280-2e70-11eb-9dd1-7a052675a130.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Safari
 - Version 14.0.1 (16610.2.11.51.8)

**Comment by chaitanyapotti** [comment]
This is a problem with uniswap and not us
