### ISSUE TITLE
iOS Safari - Unable to recover key

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1341]
Situation: 
Safari desktop testing.tor.us - Verification required
Goes to iOS Chrome beta.tor.us - Expecting to approve share but see "Verificatoin required" screen
Goes to iOS Safari beta.tor.us - Expecting to approve share but see "Cannot recover key"
Went to settings page and click "Login to tKey" 
Error shows "Cannot recover key"

I forgot my password, tried to verify via other devices but failed. I lost my tKey.
![photo_2020-11-27_17-48-13](https://user-images.githubusercontent.com/53069682/100435339-bd2f6080-30d8-11eb-9626-96fb0aed1328.jpg)

**Comment by chaitanyapotti** [comment]
Resolved
