### ISSUE TITLE
[Function] Visit uniswap.tor.us with same device (Safari) but prompted to "New Login detected"

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1343]
Situation:
Created new tKey on testing.tor.us on Safari desktop
Visit uniswap.tor.us
Connect with email
1. "New Login Detected" screen is shown (on the left image), asking me for password / verification - this is not expected as I am using the same device. I should just be logged in.
Proceed to testing.tor.us to login with my safari
2. "New Login Detected" screen is shown (on the right image), asking me to approve the request. I am using the same device so why do I need to approve the access from uniswap.tor.us?

<img width="1440" alt="Screenshot 2020-11-27 at 6 31 05 PM" src="https://user-images.githubusercontent.com/53069682/100440213-83158d00-30df-11eb-8fe3-edc521621037.png">

**Comment by chaitanyapotti** [comment]
This is because you created on testing and uniswap is using beta.
