### ISSUE TITLE
[Function] Log out from uniswap, unable to login again on Safari desktop

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1345]
Situation:
Log out from uniswap
Login
Fail to login (on safari desktop)
<img width="1440" alt="Screenshot 2020-11-27 at 6 40 25 PM" src="https://user-images.githubusercontent.com/53069682/100440677-354d5480-30e0-11eb-8c3c-fef28d00b823.png">

**Comment by chaitanyapotti** [comment]
This is a known error. Bug with web3-react.
I've raised a PR with web3-react regarding this
