### ISSUE TITLE
[Function] tKey set as default but Google acc was default during sign in on dapp

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1352]
Situation:
Connect to Torus wallet on Yearn Finance
Logged in to Google Wallet. 
However I have my tKey wallet set as default.
I would expect to be logged into my tKey, but I was logged into my Google account instead.

<img width="335" alt="Screenshot 2020-11-30 at 4 51 37 PM" src="https://user-images.githubusercontent.com/53069682/100589116-a5044f00-332d-11eb-8849-70beaa23137a.png">
<img width="567" alt="Screenshot 2020-11-30 at 5 01 54 PM" src="https://user-images.githubusercontent.com/53069682/100589324-e8f75400-332d-11eb-9c2b-4811741ce9f3.png">

**Comment by chaitanyapotti** [comment]
Fixed
