### ISSUE TITLE
[Binance Smart Chain] To update all BNB Logos

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1367]
To update all binance logo with the svg sent.
- BNB Token logo in Homepage
- BNB Token logo in activity
<img width="283" alt="Screenshot 2020-12-15 at 2 18 03 PM" src="https://user-images.githubusercontent.com/53069682/102178521-8763e780-3ee0-11eb-9b63-8cda4126f161.png">
<img width="349" alt="Screenshot 2020-12-15 at 2 21 14 PM" src="https://user-images.githubusercontent.com/53069682/102178710-da3d9f00-3ee0-11eb-9b6f-a0f15dde7247.png">

 page

**Comment by chaitanyapotti** [comment]
Done
