### ISSUE TITLE
[tKey backup phase email] Please fix fonts and wrap text

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1373]
Current:
<img width="624" alt="Screenshot 2020-12-16 at 6 28 06 PM" src="https://user-images.githubusercontent.com/53069682/102336734-86a87f80-3fcc-11eb-902e-7f8ee522b384.png">

Blur logo
A mix of Times News Romans, Roboto and Code
Wrap code, more padding
Registered member of Torus Labs. Instead of TORUS

**Comment by lionellbriones** [comment]
- logo will update after release

**Comment by lionellbriones** [comment]
Fixed on sendgrid
