### ISSUE TITLE
2 backup phrase entered, but unable to get back tKey

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1374]
Situation:
Copy and save keyshare related to device
Deleted device share
log out
log in
Enter device share-> verified
Enter tkey backup share from recovery email -> verified
But, unable to login to tkey.
<img width="1440" alt="Screenshot 2020-12-16 at 6 32 40 PM" src="https://user-images.githubusercontent.com/53069682/102337320-4a295380-3fcd-11eb-8913-e2acf5b8f0df.png">

**Comment by chaitanyapotti** [comment]
Cannot enter a deleted share
Fixed using

https://github.com/tkey/tkey/pull/59

**Comment by chaitanyapotti** [comment]
Fixed
