### ISSUE TITLE
Safari reads 2 device on tkey but chrome reads 1 device

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1376]
Situation:
Deleted device share on chrome
Recover via backup phrase + password
Save new device 
So my account on chrome has 1 device now shown on settings
<img width="508" alt="Screenshot 2020-12-16 at 6 44 16 PM" src="https://user-images.githubusercontent.com/53069682/102338622-0e8f8900-3fcf-11eb-9e20-4579840501c1.png">

Login via safari
See 2 devices on the verification page. Did safari show the device I deleted?
Not sure. There's just a mismatch in devices in tkey
<img width="667" alt="Screenshot 2020-12-16 at 6 43 25 PM" src="https://user-images.githubusercontent.com/53069682/102338778-426aae80-3fcf-11eb-9580-34a181907e96.png">

**Comment by chaitanyapotti** [comment]
No longer applicable
