### ISSUE TITLE
Update copywriting on settings page for backup phrase export

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1377]
To update copywriting to :
Note: Clearing your browser data will delete the browser from this list. Click the “   “ icon to get a copy of your backup phrase. Save this phrase for account recovery in future.

Current
<img width="550" alt="Screenshot 2020-12-16 at 6 52 40 PM" src="https://user-images.githubusercontent.com/53069682/102339365-04ba5580-3fd0-11eb-9218-ca7620d0f951.png">

To update to this
<img width="703" alt="Screenshot 2020-12-16 at 6 53 05 PM" src="https://user-images.githubusercontent.com/53069682/102339375-071caf80-3fd0-11eb-8d3b-906a3993582f.png">

**Comment by lionellbriones** [comment]
Updated on airtable
