### ISSUE TITLE
Cannot recover key error message

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1386]
I deleted my share once from the existing device. 
When I log in I keep getting "Cannot recover key" message and was unable to sign in to my key.
<img width="1440" alt="Screenshot 2020-12-22 at 1 40 15 PM" src="https://user-images.githubusercontent.com/53069682/102853618-a112ab00-445b-11eb-86ab-825bea99e990.png">
When I login to the same account on mobile chrome, it gives me the verification screen
![IMG_C5E44FD6A0F2-1](https://user-images.githubusercontent.com/53069682/102853665-b25bb780-445b-11eb-8129-75d44fdb8c1a.jpeg)

**Comment by chaitanyapotti** [comment]
Fixed
