### ISSUE TITLE
[tkey] To handle auto metadata update on tKey

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1392]
Situation:
I have 4 keyshare (OAuth, PW, Extension, Device)
I am logged in on Chrome (Device) and Extension.
On my torus wallet settings page, I delete key share from Extension
On extension, I am still able to navigate around. (metadata not updated)
Intended: User should be logged out upon the next interaction with the extension

**Comment by chaitanyapotti** [comment]
No longer applicable
