### ISSUE TITLE
[binance.tor] UI - Left and right padding to even out for seed phrase page

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1399]
To make the left and right padding even for seed phrase page
<img width="1440" alt="Screenshot 2021-01-12 at 3 46 12 PM" src="https://user-images.githubusercontent.com/53069682/104285221-3ef31600-54ee-11eb-9f2a-0617073d2dc7.png">

**Comment by lionellbriones** [comment]
Fixed
