### ISSUE TITLE
[binance.tor] To change copy to tKey instead of "Your Seed Phrase Account"

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1400]
To change copy to tKey instead of "Your Seed Phrase Account"
<img width="1440" alt="Screenshot 2021-01-12 at 3 48 05 PM" src="https://user-images.githubusercontent.com/53069682/104285272-54684000-54ee-11eb-969f-202d00b36513.png">

**Comment by chaitanyapotti** [comment]
i don't think we should do that.
Tkey accounts and seed phrase accounts are distinct and should be differentiated in the UI as well.
You can only have one Tkey account but multiple seed phrase accounts.
The new scheme for naming should be consistent across binance.tor.us and app.tor.us

**Comment by itsinz** [comment]
There is multiple inconsistency in this
For onboarding: We ask users to set up tKey and yet it turns into a seed phrase account
For Binance extension, their account is labelled as tKey and all accounts comes with seed phrase.

The overall in-charge of this tKey product should shed some light on this.

**Comment by chaitanyapotti** [comment]
No longer applicable
