### ISSUE TITLE
[app.tor] to update seed phrase icon upon creation

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1403]
To update the seed phrase icon in settings page. Currently it shows google icon after clicking create account
<img width="249" alt="Screenshot 2021-01-12 at 5 20 42 PM" src="https://user-images.githubusercontent.com/53069682/104295593-a06db180-54fb-11eb-8d13-1cda08ca3ec8.png">

**Comment by lionellbriones** [comment]
Fixed
