### ISSUE TITLE
Giveth is misspelled on the parteners page

### ISSUE THREAD

**Issue by GriffGreen** [torusresearch/torus-website#1428]
https://tor.us/partners.html

<img width="369" alt="Screen Shot 2021-01-27 at 11 22 52 AM" src="https://user-images.githubusercontent.com/14945613/106021671-5244da80-60c5-11eb-8031-b6fa17ba6097.png">

It is currently written as "GiveETH", it should be "Giveth"

Thank you!!

**Comment by chaitanyapotti** [comment]
Fixed. Thanks for reporting
