### ISSUE TITLE
Getting 404 on an image while using torus-embed

### ISSUE THREAD

**Issue by kanishkatn** [torusresearch/torus-website#1437]
Hi, 

I am getting a 404 while using torus-embed. It gets logged right after signing a transaction in app.tor.us

404 path: https://app.tor.us/v1.9.9/img/icons/close.svg

<img width="1792" alt="Screenshot 2021-02-16 at 12 09 02 PM" src="https://user-images.githubusercontent.com/4919645/108017430-d4367c80-704f-11eb-8066-59b84732037f.png">

**Comment by chaitanyapotti** [comment]
Fixed
