### ISSUE TITLE
ERR_ACTION_ACCESS_UNDEFINED: Are you trying to access this.someMutation() 

### ISSUE THREAD

**Issue by ligi** [torusresearch/torus-website#1439]
when clicking on confirm in https://beta.openlogin.com/register
I get the email but cannot escape the screen - confirm button does nothing

![Selection_477](https://user-images.githubusercontent.com/111600/108722390-65f82b00-7523-11eb-9bdf-d46854839415.png)

**Comment by chaitanyapotti** [comment]
Fixed now
