### ISSUE TITLE
Token symbol displayed incorrectly on Matic testnet

### ISSUE THREAD

**Issue by bitbeckers** [torusresearch/torus-website#1441]
**Describe the bug**
The value of the transaction and the token symbol are displayed incorrectly when prompted with the 'sign transaction' modal

'Total cost' is in ETH
'You send' is in ETH
The value of the transaction seems correct since the ~ ... USD field matches the expectation. 

**To Reproduce**
Use Torus-embed in repo

Config:
```
    await web3Helper.torus.init({
      buildEnv: "production", 
      enableLogging: torusLogging, 
      network: {
        host: "mumbai", 
        chainId: 80001, 
        networkName: "Mumbai Test Network", 
      },
      showTorusButton: true,
    });
```

Send transaction

**Expected behavior**
The symbol of the token should update depending on the network used

**Screenshots**
Shared on Telegram and just uploaded here: https://ibb.co/wc842tx

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox, Brave
 - Version OS Mojave, browser latest

**Additional context**

**Comment by chaitanyapotti** [comment]
This is fixed in v1.9.10 release
