### ISSUE TITLE
Can't switch OpenLogin wallet to default

### ISSUE THREAD

**Issue by phuctm97** [torusresearch/torus-website#1483]
**Describe the bug**

Clicking on 'Switching this to default' on OpenLogin wallet does nothing

**To Reproduce**

1. Login, Go to 'Settings'
3. Scroll down to 'Account Management'
3. Click on 'Switch this to default' next to OpenLogin wallet
4. It does nothing

**Expected behavior**

OpenLogin wallet should be set as default

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by chaitanyapotti** [comment]
Fixed in develop
