### ISSUE TITLE
Unable to Log into Google Wallet on app.tor.us

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#1487]
**Describe the bug**
I am unable to access my Google wallet through app.tor.us.

**To Reproduce**
1. Go to https://app.tor.us
2. Login with Google
3. Only Webauthn is prompted
4. Logged into OpenLogin wallet, without access to the Google wallet 

**Expected behavior**
Would expect to be able to log into my Google wallet.

**Screenshots**
![Screenshot 2021-04-22 at 11 44 02 AM](https://user-images.githubusercontent.com/51352241/115652547-0b7f1d80-a360-11eb-9c06-77f3911805be.png)
![Screenshot 2021-04-22 at 11 14 03 AM](https://user-images.githubusercontent.com/51352241/115652519-00c48880-a360-11eb-99f7-d92a06010114.png)

**Desktop (please complete the following information):**
 - Device: Macbook Pro
 - OS: MacOS Big Sur
 - Browser: Chrome
 - Version: Version 89.0.4389.128 (Official Build) (x86_64)

**Comment by chaitanyapotti** [comment]
Fixed
