### ISSUE TITLE
Force User to Update Client whenever a new version of Torus is pushed out.

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#1503]
**Is your feature request related to a problem? Please describe.**
Users who don't have the latest versions of Torus on their computer have to do hard reloads, clear their cache, reset their service workers etc.

**Describe the solution you'd like**
When there is a new version of Torus pushed out, and the user's client isn't the most up to date, throw a pop-up that forces a hard reload on the client, clear cache, reset their service workers etc. to use the latest version of Torus.

**Comment by chaitanyapotti** [comment]
It's fixed now
