### ISSUE TITLE
Torus Wallet only showing ETH balance in total value

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1523]
**Describe the bug**
Torus Wallet shows ETH balance in Total Value. Other coins have 0 USD and their value are not included in Total Value in the wallet

**To Reproduce**
Login to app.tor.us, wallet homepage.

**Expected behavior**
Total value to reflect the value of all coins in the wallet

**Screenshots**
![Screenshot 2021-05-24 at 11 51 20 AM](https://user-images.githubusercontent.com/53069682/119294295-b5670800-bc86-11eb-9026-41c52cb080a4.png)
![Screenshot 2021-05-24 at 11 51 04 AM](https://user-images.githubusercontent.com/53069682/119294302-b7c96200-bc86-11eb-815d-e485bd8d52f9.png)

**Comment by itsinz** [comment]
Corrected: Now I revisit my wallet page and the total value reflects actual amount in wallet. 
So the updated problem here is that the wallet takes too long to load wallet total value

**Comment by chaitanyapotti** [comment]
Price api failed. It's better now
