### ISSUE TITLE
More than 10 seconds for transaction update modal to come up on Torus Wallet

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1532]
**Describe the bug**
Transfer ETH. Confirm. It took more than 10 seconds for the Sent modal to come up the screen.

**To Reproduce**
Transfer money on torus wallet
Transfer -> Confirm -> Wait for more than 10 seconds -> Modal appear

**Expected behavior**
Modal to appear instantly upon confirming the transaction

**Screenshots**
![Screenshot 2021-06-01 at 5 52 50 PM](https://user-images.githubusercontent.com/53069682/120306161-28662380-c304-11eb-8bd5-d5de06c1b29d.png)

**Desktop (please complete the following information):**
MacOS, Chrome

**Comment by chaitanyapotti** [comment]
Fixed
