### ISSUE TITLE
Private key download doesn't work

### ISSUE THREAD

**Issue by vyomshm** [torusresearch/torus-website#1554]
**Describe the bug**
I could not download an encrypted soft copy of my private key via settings.

**To Reproduce**
1. Go to 'Settings' in the topbar
2. Click on 'Account details'
3. Click on 'Download soft copy (JSON)'  download icon button
4. Enter `qwerty` as encryption password -> click 'confirm'
5. The encrypting loader spins for a time and then stops but with no file downloaded and no error message.

**Expected behavior**
An encrypted private key json file should be downloaded or an error message should be displayed

**Screenshots**
![bug_screenshot](https://user-images.githubusercontent.com/20184946/121800441-858c9e00-cc4f-11eb-93e2-104839881c97.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser - Tested on both Safari & Chrome

**Comment by chaitanyapotti** [comment]
Fixed
