### ISSUE TITLE
Edit 1559 tooltip copywriting

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1647]
**Describe the bug**
Edit 1559 tooltip copywriting on testing.

Change "But most of the time" to "Usually"
<img width="307" alt="Screenshot 2021-08-23 at 12 19 29 PM" src="https://user-images.githubusercontent.com/53069682/130389864-d5e4c3d9-6e8f-4e3c-8264-b8f31a1d5708.png">
Remove repeated "the"
<img width="315" alt="Screenshot 2021-08-23 at 12 18 39 PM" src="https://user-images.githubusercontent.com/53069682/130390101-66662a54-7c4a-41dc-95b3-4e4652ef10b9.png">

**Comment by himanshuchawla009** [comment]
airtable updated @itsinz
