### ISSUE TITLE
Base fee not shown on advanced options

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1652]
Base fee not shown on advanced options
Current
<img width="368" alt="Screenshot 2021-08-23 at 1 02 20 PM" src="https://user-images.githubusercontent.com/53069682/130392997-82ded30d-7322-4250-905f-e2363f565149.png">

On figma:
<img width="385" alt="Screenshot 2021-08-23 at 1 00 49 PM" src="https://user-images.githubusercontent.com/53069682/130392944-102f6bcb-1829-4423-b38e-4592674d84be.png">

**Comment by chaitanyapotti** [comment]
This is intended because base fee is set by network and can change by the tx is confirmed on chain. The estimate shown might wildly change and cause confusion to the user.
