### ISSUE TITLE
Estimated transfer time does not make sense

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1653]
Attempting to transfer NFT.
Estimated max gas fee does not make sense. With 0.03USD price difference, and no price difference between medium and low
<img width="346" alt="Screenshot 2021-08-23 at 1 11 49 PM" src="https://user-images.githubusercontent.com/53069682/130393769-35b54e86-a571-491f-b3ec-d8595024b67e.png">

**Comment by chaitanyapotti** [comment]
Api basis
