### ISSUE TITLE
logo not showing up on login footer on safari

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1654]
1. logo not showing up on login footer on safari
2. To update T&Cs and privacy policy on footer

On safari
<img width="1202" alt="Screenshot 2021-08-23 at 2 52 42 PM" src="https://user-images.githubusercontent.com/53069682/130406278-500a3236-792a-449e-84f1-f5b092dcfc20.png">

On chrome (this is the right one)
<img width="1201" alt="Screenshot 2021-08-23 at 2 53 38 PM" src="https://user-images.githubusercontent.com/53069682/130406245-7ee2eee9-6048-4c11-9ae7-06f50fab7d4c.png">

**Comment by chaitanyapotti** [comment]
Click enable images in safari developer settings. 
Not an issue anymore. Tested
