### ISSUE TITLE
Green check not showing on safari when transaction is sent

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1655]
On safari: 
<img width="356" alt="Screenshot 2021-08-23 at 3 22 23 PM" src="https://user-images.githubusercontent.com/53069682/130406853-6f50fb19-124c-40ae-a1e7-446528b27474.png">

On chrome (correct)
![image](https://user-images.githubusercontent.com/53069682/130406777-b12f29c8-24a6-404a-b339-e018398497c4.png)

**Comment by chaitanyapotti** [comment]
Need to allow images in safari developer settings.
