### ISSUE TITLE
iOS Chrome - Having problem to relogin

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1660]
- Logged in to vue-embed.tor.us to test.
- Logout 
- Login to test Send ETH onwards -> Unable to login, login modal does not come up, stuck on page

![IMG_974A2DA6C2F4-1](https://user-images.githubusercontent.com/53069682/130426920-fd640593-590e-4eed-9f17-08aeea9ba931.jpeg)
![IMG_9EEB1A8A693C-1](https://user-images.githubusercontent.com/53069682/130426947-d62d3f6a-46eb-4f0c-9da6-48d78e367011.jpeg)
>> tried reloading / visit testing.tor.us and come back, still does not work

**Comment by chaitanyapotti** [comment]
Hard reload Vue embed. 
Not an issue anymore. Tested
