### ISSUE TITLE
vue-embed send dai and send ETH default max tx fee inconsistent

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1670]
[Edge]
On vue embed, Send ETH and Send Dai, 
Upon selecting the Max Tx fee, the default (medium)radio button is not selected. The amount is also not medium, it is the minimum (0.067usd).

Expected: Radio button to be select on medium and amount is the amount stated in medium for max transaction fee
<img width="386" alt="Screenshot 2021-08-25 at 9 58 32 AM" src="https://user-images.githubusercontent.com/53069682/130713984-a9dfb50a-c7d0-4017-adbc-405476ba5d6f.png">
<img width="430" alt="Screenshot 2021-08-25 at 9 58 28 AM" src="https://user-images.githubusercontent.com/53069682/130713992-250c678e-0ad8-4ac4-9d59-e508befd1128.png">

**Comment by itsinz** [comment]
This also happens on Brave, where the Max Transaction Fee states 0.067USD but upon clicking edit, 0.067USD is not one of the low, med, high options
<img width="370" alt="Screenshot 2021-08-25 at 10 13 29 AM" src="https://user-images.githubusercontent.com/53069682/130715361-5c499960-3d66-406b-b620-a4f266886b5d.png">

**Comment by lionellbriones** [comment]
This happens because the Transaction Fee is already set on torus-embed transactions.

**Comment by chaitanyapotti** [comment]
Lionell said it right. Torus embed sets its own fees.
