### ISSUE TITLE
Brave: To block banner

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#1672]
Is it possible to block the brave banner "Would you like to start crypto wallet..."?

It appears at every load of Torus wallet
<img width="1440" alt="Screenshot 2021-08-25 at 10 09 54 AM" src="https://user-images.githubusercontent.com/53069682/130714814-431cc8f9-6ec6-4a52-afd3-166341613e65.png">

**Comment by chaitanyapotti** [comment]
It's a browser thing. We can't do anything about it
