### ISSUE TITLE
Torus Wallet activity page filter is missing information

### ISSUE THREAD

**Issue by vacwt** [torusresearch/torus-website#1943]
**Describe the bug**
Filter missing 'date' , currently it only says 'All' which is not descriptive on what that filter is for

**To Reproduce**
1. Go to 'app.tor.us'
2. Click on 'activity'
3. Filter only says 'All'

**Expected behavior**
Filter should state 'All **_Dates_**'

**Screenshots**
<img width="1912" alt="Screenshot 2022-05-11 at 12 44 58 PM" src="https://user-images.githubusercontent.com/96512357/167770903-651de600-045a-47c9-a22c-c1e46ebf3217.png">
<img width="551" alt="Screenshot 2022-05-11 at 12 46 36 PM" src="https://user-images.githubusercontent.com/96512357/167771061-8209cf10-7e9c-4e16-82cf-f3b767a59468.png">

**Comment by lionellbriones** [comment]
Updated on airtable. should reflect on next production deploy
