### ISSUE TITLE
Random Youtube Link when logging in via gmail in incognito mode

### ISSUE THREAD

**Issue by Jiafanggg** [torusresearch/torus-website#1952]
**Describe the bug**
After logging in to Torus Wallet using Gmail, while the backend is trying to authenticate the user's credentials, the frontend (browser link area) displays YouTube link & YouTube logo before redirecting the user to the Torus Wallet page. 

**To Reproduce**
1. Open an incognito browser on Safari 
2. Log in using the Gmail option
3. Enter your email & password
4. See error on the tab 

**Expected behavior**
There should not be any Youtube Link/ YouTube logo that is displayed on the tab/ link area when redirecting the user to the page.

**Screenshots**
<img width="1440" alt="Screenshot 2022-05-23 at 1 37 23 PM" src="https://user-images.githubusercontent.com/72696667/169750522-45ece70a-0d87-468a-ad13-9adaa9791228.png">
<img width="1440" alt="Screenshot 2022-05-23 at 1 37 45 PM" src="https://user-images.githubusercontent.com/72696667/169750564-5d354af5-2856-4ef6-b11f-0a706bb3237c.png">

**Desktop (please complete the following information):**
 - OS: 11.6.5
 - Browser: Safari
 - Version: 15.4

**Comment by chaitanyapotti** [comment]
so, that's how google manages logins.. it's via accounts.youtube.com
