### ISSUE TITLE
Wrong Copy on Permissions Window

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#286]
<img width="497" alt="Screenshot 2019-07-30 at 4 56 49 PM" src="https://user-images.githubusercontent.com/51352241/62115552-32bfcc80-b2eb-11e9-9700-1943beb70600.png">

Accessed this window after logging into the DApp and signing for the transaction.

Change "Permission" Title to "Grant Permission"
The title can prompt user action, and they would know what decisions they're making/approving

Change "Sample Text Here" to default copy that DApps can use.

Copy suggestion for detailed information:
Prove to "DApp name" that you are the owner of this account.
"DApp name"/The DApp requires your permission to conduct transactions with your wallet.

**Comment by chaitanyapotti** [comment]
Fixed
