### ISSUE TITLE
[Top up Screen] 'Write to us' link not working

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#287]
<img width="207" alt="Screenshot 2019-07-31 at 2 41 49 PM" src="https://user-images.githubusercontent.com/53069682/62189756-690c5300-b3a2-11e9-936a-7d226922df20.png">
Please activate the email torus function when clicked onto the 'Write to us' Text

Email : hello@tor.us

**Comment by chaitanyapotti** [comment]
Fixed
