### ISSUE TITLE
[Settings] 'DApp' instead of 'Daap'

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#288]
<img width="216" alt="Screenshot 2019-07-31 at 3 21 42 PM" src="https://user-images.githubusercontent.com/53069682/62191848-010c3b80-b3a7-11e9-8135-21b02940543f.png">

Please amend the copy from 'Daap' to 'DApp'

**Comment by chaitanyapotti** [comment]
Fixed
