### ISSUE TITLE
Unable to recognise the switch between networks (CryptoKitties)

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#293]
Note: CryptoKitties only works on the Main Ethereum Network

**Summary**
CryptoKitties only supports Main Eth Network and when Torus account was on some other network before logging in, problems will occur. 
CryptoKitties does not respond to the network change done on Torus.
It only responds if you restart the app and log in again while already logged in using the Main Eth Network.

**Scenario 1:**  (Before creating account)
https://www.cryptokitties.co/sign-in?redirect_url=L215LWtpdHRpZXM%3D
Tried logging in while on Rinkeby previously thus I was prompted to switch
![Screenshot 2019-07-31 at 2 51 15 PM](https://user-images.githubusercontent.com/51191261/62190147-3adb4300-b3a3-11e9-96fe-66cd1f2569c4.png)
After changing it back to Main Eth Network, I'm asked to sign up but both "Sign Up" and "Start" buttons are not responsive (I am still logged in with Torus as seen at the bottom left but no wallet is detected)
![Screenshot 2019-07-31 at 2 52 34 PM](https://user-images.githubusercontent.com/51191261/62190131-2f881780-b3a3-11e9-9b8b-b4748bc0c8c6.png)

**Scenario 2:** (after creating account)
Logged in using Torus but wallet not detected
![Screenshot 2019-07-31 at 3 46 52 PM](https://user-images.githubusercontent.com/51191261/62193531-847b5c00-b3aa-11e9-986f-51416cdae99c.png)
Wallet detected only after a forced restart
![Screenshot 2019-07-31 at 3 47 09 PM](https://user-images.githubusercontent.com/51191261/62193568-96f59580-b3aa-11e9-84d7-0981f099711f.png)
Afterward, you'll be prompted to switch to Main Eth Network if you are not. 
However after switching, website would still be unresponsive

**Comment by chaitanyapotti** [comment]
Fixed
