### ISSUE TITLE
Vertical scroll bars on the transaction status modal

### ISSUE THREAD

**Issue by tetratorus** [torusresearch/torus-website#300]
Modal appears after a transaction has been sent and has a vertical scroll bar. There should be no scroll bars there, modal should just fit

**Comment by lionellbriones** [comment]
<img width="329" alt="Screen Shot 2019-08-01 at 2 02 58 PM" src="https://user-images.githubusercontent.com/4738957/62269292-29f30600-b465-11e9-8246-4d89dc265b2d.png">
is this the modal @tetratorus? I think it's ok now

**Comment by chaitanyapotti** [comment]
Fixed
