### ISSUE TITLE
Unable to buy Blockchain Cutie

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#304]
Basically, whenever I try to purchase a cutie, the site shows a blank screen 
![Screenshot 2019-07-31 at 4 46 12 PM](https://user-images.githubusercontent.com/51191261/62197674-dfb14c80-b3b2-11e9-9298-187f7c21b7b8.png)

Instead of this page:
![Screenshot 2019-07-31 at 4 46 46 PM](https://user-images.githubusercontent.com/51191261/62197782-0ff8eb00-b3b3-11e9-80f9-728609a31ab6.png)

You may ask if I refreshed, haha yes I did and that's how I got the second page however it only shows for a split second before turning to the first page, blank... 
Not sure if this is our fault or just the cuties don't want to be bought.

**Comment by chaitanyapotti** [comment]
Fixed
