### ISSUE TITLE
When search does not exist, Last Updated still wraps to the next line

### ISSUE THREAD

**Issue by YZhenY** [torusresearch/torus-website#307]
![image](https://user-images.githubusercontent.com/25172440/62203809-7a635880-b3be-11e9-8c3e-182509f30c20.png)

**Comment by rathishubham7** [comment]
fixed

**Comment by chaitanyapotti** [comment]
This made the currency dropdown look bad

**Comment by chaitanyapotti** [comment]
No, the currency dropdown still looks spaced and the entire app is not 12-column now and is using the whole screen in max width
@lionellbriones please look into this
