### ISSUE TITLE
[Account] To show email instead of wallet address

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#312]
<img width="400" alt="Screenshot 2019-08-01 at 1 44 52 PM" src="https://user-images.githubusercontent.com/53069682/62268518-aafcce00-b462-11e9-87e8-fc3bed9de54a.png">

To show email address.
Reveal wallet address only upon clicking the eye icon

**Comment by chaitanyapotti** [comment]
Shows email now
