### ISSUE TITLE
[Transaction Speed] Both options are the same, should be different

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#315]
<img width="618" alt="Screenshot 2019-08-01 at 2 30 04 PM" src="https://user-images.githubusercontent.com/53069682/62270574-e8fcf080-b468-11e9-981a-83a1c2c1589f.png">

Transaction Speed and values are the same for both options. Should be different.

**Comment by chaitanyapotti** [comment]
Some problem with the api provider. The code is correct on our end. it will be fixed by the api provider soon.
