### ISSUE TITLE
[Advanced Options] To include New Estimated Time 

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#316]
Current : 

<img width="629" alt="Screenshot 2019-08-01 at 2 55 04 PM" src="https://user-images.githubusercontent.com/53069682/62271923-6fff9800-b46c-11e9-8ad5-e8fd970c7e78.png">

Refer to below for adding new estimated time:

<img width="599" alt="Screenshot 2019-08-01 at 2 56 23 PM" src="https://user-images.githubusercontent.com/53069682/62271975-8dccfd00-b46c-11e9-87fd-bd34a2773867.png">

**Comment by chaitanyapotti** [comment]
No reliable way to estimate the new time

**Comment by itsinz** [comment]
Understand, but the time still needs to be shown (regardless accurate or not) so users know how the change in gas price affects the transaction speed.

**Comment by chaitanyapotti** [comment]
Can be closed
