### ISSUE TITLE
[Transaction Activity] Transaction Type and Amount does not show

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#317]
<img width="1244" alt="Screenshot 2019-08-01 at 2 57 42 PM" src="https://user-images.githubusercontent.com/53069682/62272136-ee5c3a00-b46c-11e9-8ce7-df78c2b716fa.png">

Transaction type and amount does not show.

**Comment by itsinz** [comment]
Transaction Type is showing but amount still doesnt show

**Comment by chaitanyapotti** [comment]
Fixed several other things which are hardcoded in tx history table
