### ISSUE TITLE
[Transfer Value] Round off ETH to 5 dp

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#318]
<img width="1250" alt="Screenshot 2019-08-01 at 3 25 07 PM" src="https://user-images.githubusercontent.com/53069682/62273878-37ae8880-b471-11e9-8611-50e6e955e118.png">

Round off 2dp for USD (3dp if the value is too small)
Round off 5dp for ETH if value is lesser than 1.

**Comment by YZhenY** [comment]
fixed
