### ISSUE TITLE
Transactions not on mainnet showing as mainnet transactions

### ISSUE THREAD

**Issue by YZhenY** [torusresearch/torus-website#319]
![image](https://user-images.githubusercontent.com/25172440/62291654-199d5400-b482-11e9-8db6-85cee86988b8.png)

https://ropsten.etherscan.io/tx/0x3368543623647847e7c0d5b7870d66a5593cee5836a94d0adaf5efb6d3749fff

**Comment by YZhenY** [comment]
formatting is a tad funky too

**Comment by chaitanyapotti** [comment]
Fixed it
