### ISSUE TITLE
Gas Limit is not handed over from WalletTransfer to TransferConfirm Screen

### ISSUE THREAD

**Issue by YZhenY** [torusresearch/torus-website#320]
![image](https://user-images.githubusercontent.com/25172440/62296320-73a31700-b48c-11e9-9351-0eb672bcb12b.png)

**Comment by YZhenY** [comment]
![image](https://user-images.githubusercontent.com/25172440/62296516-dd232580-b48c-11e9-979d-8b9a79800051.png)
or gas limit seems not even saved for that matter

**Comment by chaitanyapotti** [comment]
Fixed in #328
