### ISSUE TITLE
Improve feedback on transactions thorugh dapps

### ISSUE THREAD

**Issue by YZhenY** [torusresearch/torus-website#329]
right now when we submit a tx, we just close the page. Dapps need some way to interact after a tx has been submitted or we need some way to notify a user of the submission:

a possible way might be a chrome web notification, or perhaps the embedded iframe popping something up

**Comment by itsinz** [comment]
Option 1 : Chrome Web notification
<img width="692" alt="Screenshot 2019-08-02 at 11 30 05 AM" src="https://user-images.githubusercontent.com/53069682/62342326-04273900-b519-11e9-85b2-2b474816de37.png">

Option 2 : Embedded iframe
<img width="687" alt="Screenshot 2019-08-02 at 11 30 13 AM" src="https://user-images.githubusercontent.com/53069682/62342294-ee197880-b518-11e9-800f-65990068e71a.png">

**Comment by chaitanyapotti** [comment]
Let's use the chrome web notification

**Comment by rathishubham7** [comment]
fixed.
