### ISSUE TITLE
[Torus Wallet] Unable to make a purchase on Cryptokitties

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#336]
<img width="1438" alt="Screenshot 2019-08-02 at 12 53 18 PM" src="https://user-images.githubusercontent.com/53069682/62345364-ad276100-b524-11e9-93a6-9f487caaca2f.png">
Unable to make a purchase/start the game despite being connected to Torus wallet.
Site says 'No Wallet'

**Comment by chaitanyapotti** [comment]
Please check network. You must be on mainnnet for cryptokitties to work

**Comment by lionellbriones** [comment]
Yes, i tried on main network and it's working

**Comment by chaitanyapotti** [comment]
Great
