### ISSUE TITLE
[Homepage] Align the Navigation with Header

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#339]
Current : 
<img width="754" alt="Screenshot 2019-08-02 at 3 41 56 PM" src="https://user-images.githubusercontent.com/53069682/62353322-00a5a900-b53d-11e9-9632-c6542133d2ab.png">

Ideal : 
<img width="670" alt="Screenshot 2019-08-02 at 3 49 12 PM" src="https://user-images.githubusercontent.com/53069682/62353368-187d2d00-b53d-11e9-811f-ae2972a7488e.png">

**Comment by chaitanyapotti** [comment]
Fixed
