### ISSUE TITLE
[Homepage] Make currency and Dapp card the same size

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#340]
Current : 
<img width="751" alt="Screenshot 2019-08-02 at 3 43 39 PM" src="https://user-images.githubusercontent.com/53069682/62353413-3480ce80-b53d-11e9-96d2-ace9edd15fa4.png">

Ideal : 
<img width="790" alt="Screenshot 2019-08-02 at 3 59 39 PM" src="https://user-images.githubusercontent.com/53069682/62354043-8fff8c00-b53e-11e9-9a36-0d66a50b4700.png">

**Comment by chaitanyapotti** [comment]
Fixed
