### ISSUE TITLE
[Transfer] Unsuccessful modal not supposed to show

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#341]
Please remove Unsuccessful modal
It was shown when user click cancel at Transaction Summary.
From this 
<img width="502" alt="Screenshot 2019-08-02 at 4 02 24 PM" src="https://user-images.githubusercontent.com/53069682/62354265-07352000-b53f-11e9-9e2d-48720397bd99.png">

Click cancel, this will be shown. Please remove this. and user is just supposed to return to transfer page

<img width="752" alt="Screenshot 2019-08-02 at 3 46 56 PM" src="https://user-images.githubusercontent.com/53069682/62354380-41062680-b53f-11e9-9a56-9ae7108d48d4.png">

**Comment by chaitanyapotti** [comment]
Fixed
