### ISSUE TITLE
Unable to Transfer ETH on Safari on iOS

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#386]
The Continue button for transferring ETH is unresponsive on Safari on iOS, and I am unable to proceed with the transfer.

![IMG_7466](https://user-images.githubusercontent.com/51352241/63239446-be3ed480-c27d-11e9-82a9-c58879472e01.PNG)

**Comment by chaitanyapotti** [comment]
It is possible to transfer. Please allow popups in settings of safari
