### ISSUE TITLE
Transaction History Broken

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#421]
Unable to view any transaction history (All Transactions, Send, Receive) from 17 August 2019 onwards.

<img width="1221" alt="Screenshot 2019-08-25 at 2 39 07 PM" src="https://user-images.githubusercontent.com/51352241/63650036-25f59380-c746-11e9-8d3f-bd1d55754a60.png">

**Comment by chaitanyapotti** [comment]
Unable to replicate

**Comment by chaitanyapotti** [comment]
Working now
