### ISSUE TITLE
[Activity Page] Filter for "Receive" and Period filter does not work

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#452]
<img width="1288" alt="Screenshot 2019-09-18 at 5 35 15 PM" src="https://user-images.githubusercontent.com/53069682/65136830-d7809f80-da3a-11e9-98c0-0b82716d7a6c.png">
Please fix activity page. When filter to view "Receive" there is no transaction available. 

Filter by period does not work too. Unable to filter transaction for the past 1 week and 1 month

**Comment by chaitanyapotti** [comment]
Filters do work but tx history has problems
