### ISSUE TITLE
Transaction history not reflected in Activity.

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#473]
**Describe the bug**
Transaction history not reflected in activity section.

**Screenshots**

<img width="1222" alt="Screenshot 2019-10-02 at 2 44 09 PM" src="https://user-images.githubusercontent.com/51352241/66022073-c8641c00-e527-11e9-9ff8-631c244f646f.png">
<img width="1138" alt="Screenshot 2019-10-02 at 2 43 41 PM" src="https://user-images.githubusercontent.com/51352241/66022074-c8fcb280-e527-11e9-91f3-dcd25c41b4e0.png">

**Comment by chaitanyapotti** [comment]
Duplicate
