### ISSUE TITLE
[Confirmation Screen] Turns translucent, please keep it full white

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#488]
<img width="502" alt="Screenshot 2019-10-09 at 8 53 01 AM" src="https://user-images.githubusercontent.com/53069682/66443687-99433280-ea72-11e9-993e-1565493eb053.png">
<img width="499" alt="Screenshot 2019-10-09 at 8 52 23 AM" src="https://user-images.githubusercontent.com/53069682/66443688-99433280-ea72-11e9-9a11-c15115a12194.png">
Confirmation screen turns translucent when click on more details during transfer and also after clicking confirm. Unable to read text. Please make it white again.

**Comment by chaitanyapotti** [comment]
@lionellbriones I believe this is already fixed. pls confirm

**Comment by lionellbriones** [comment]
> @lionellbriones I believe this is already fixed. pls confirm

Yes it's fixed
