### ISSUE TITLE
Building error handling structure

### ISSUE THREAD

**Issue by YZhenY** [torusresearch/torus-website#49]
Right now errors triggered in the iframe context stay in the iframe context - unreachable to the dapp operating.

We need decide on a structure to handle the errors (through the streams) such that they are standardised, transported to the dapp and can be managed properly by dapp the dapp. Also to inherit metamask logs.

**Comment by tetratorus** [comment]
this is fixed, we already propagate errors to the front end, let's reopen the issue under hooks for window on-close
