### ISSUE TITLE
Should display network connectivity status!

### ISSUE THREAD

**Issue by Jaimeloeuf** [torusresearch/torus-website#539]
The connectivity status of the network should be shown, so that the user know if the app is able to connect to the network that they are on. This has been observed as I was testing with my local Ganache chain.

Upon connecting to the local chain, there is nothing shown to indicate the network connectivity status, so one would assume that it works, and navigate to Home page expecting to see my Eth show up as I know that I would have eth in the imported account of my local chain. But if the network connection fails and unable to show the result, the default ETH value of 0 is shown, which will make me suspect that there are other errors instead of just being unconnected.

Thus suggestion is to create a display section to indicate network status to the user. Currently the only way to find out about the error is to check the developer console for connection errors. View below attached images for more information.

![Should have a connection indicator somewhere here, either in homepage or better still in th navigation bar directly](https://user-images.githubusercontent.com/44993072/68015864-23776300-fcce-11e9-8942-1b8786c19533.png)
^Should have a connection indicator somewhere here, either in homepage or better still in th navigation bar directly.

![Connection status only viewable via developer console](https://user-images.githubusercontent.com/44993072/68015852-19556480-fcce-11e9-83b3-142da5237cfb.png)
^Connection status only viewable via developer console.

**Comment by itsinz** [comment]
<img width="656" alt="Screenshot 2019-11-04 at 3 47 39 PM" src="https://user-images.githubusercontent.com/53069682/68105866-cb816c00-ff1a-11e9-9bee-90f3e55da672.png">
We could add the network beside My Wallet, Kindly refer to image above for reference

However, do note that this is only relevant to advance users, beginners will not know what this means.

Hence, we could have this "Display Network in Homepage" Yes No Radio Button under settings.

Pending review/comments.

**Comment by Jaimeloeuf** [comment]
Looks good, but was thinking more of a, “connected 😁” or “not connected 😩” indicator rather than simply the network name.

Maybe we could do, “not connected” and “network_name”? The toggle in setting idea is great!

**Comment by itsinz** [comment]
<img width="575" alt="Screenshot 2019-11-04 at 5 30 44 PM" src="https://user-images.githubusercontent.com/53069682/68110910-db07b180-ff28-11e9-986d-5fd230ed30f2.png">
Network to be coloured when connected and it can be grey with assisting text to indicate it is not connected with the revised image.

**Comment by carloslastresDev** [comment]
Let me take a look

**Comment by carloslastresDev** [comment]
We can go with something like this:
![image](https://user-images.githubusercontent.com/15041375/68114957-430ec580-ff32-11e9-88f5-b074896de1c7.png)
&
![image](https://user-images.githubusercontent.com/15041375/68114965-4609b600-ff32-11e9-9434-6b87041384a8.png)

**Comment by Jaimeloeuf** [comment]
Looks great! I assume it will be side by side to the "My Wallet" when it is on mobile?

**Comment by iamonuwa** [comment]
> Looks great! I assume it will be side by side to the "My Wallet" when it is on mobile?

+1 @Jaimeloeuf
