### ISSUE TITLE
Activity Transaction History not accurate

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#540]
Transaction history is not reflective of the data shown on Etherscan, but shows transactions as unsuccessful instead.

<img width="1150" alt="Screenshot 2019-11-01 at 5 45 49 PM" src="https://user-images.githubusercontent.com/51352241/68016458-97fed180-fccf-11e9-9c09-867733f20579.png">

<img width="1112" alt="Screenshot 2019-11-01 at 5 47 25 PM" src="https://user-images.githubusercontent.com/51352241/68016524-be247180-fccf-11e9-8bf2-954acbf98f6c.png">

**Comment by chaitanyapotti** [comment]
Fixed now
