### ISSUE TITLE
Network "Save" button should have a UI feedback on-click/on-save to indicate success/error to the user.

### ISSUE THREAD

**Issue by Jaimeloeuf** [torusresearch/torus-website#541]
The "save" button in the network section of the settings tab should have a UI feedback/response to the user when it is clicked, so that the user would be able to know if the save action succeeded or failed.

Issue faced when setting custom RPC connection, which after editing requires a press of the save button, but since the save button do not auto close the drop down options editor or show a success/error indicator, the user would not know if the action was successful, and the because of this, the button looks as if it does not do anything at all.

Below attached are images illustrating the issue:
![Screenshot (93)](https://user-images.githubusercontent.com/44993072/68016325-4fdfaf00-fccf-11e9-85ed-d896a331c1cb.png)
^When the button is clicked, there is no UI feedback triggered onClick when the user wants to save the connection details

![Screenshot (92)](https://user-images.githubusercontent.com/44993072/68016322-4d7d5500-fccf-11e9-86b0-1b3f31be0658.png)
^After the button is let go off, there is still no UI feedback triggered, showing the exact same drop down menu and all which seems to indicate that the button is not working despite the button actually performing the action.

![Screenshot (94)](https://user-images.githubusercontent.com/44993072/68016453-93d2b400-fccf-11e9-91ec-a28283136efd.png)
^ The only way to check if the save was successful, is to switch tab over to either home like what I did as per the image above or whichever, before switching back to the settings page to look at the network's section. The change is then reflected after this navigation.

**Comment by itsinz** [comment]
<img width="727" alt="Screenshot 2019-11-04 at 4 19 53 PM" src="https://user-images.githubusercontent.com/53069682/68107188-fd94cd00-ff1e-11e9-830d-144e1783cec1.png">
Noted and agree.

Kindly find the notification for Network and Display in image above.

**Comment by Jaimeloeuf** [comment]
Looks good, but I was referring more to, having the details drop down, close back up. But both is good, seems understandable.

**Comment by carloslastresDev** [comment]
Thanks for the good feedback JJ. I'll take a look at this too

**Comment by carloslastresDev** [comment]
I like the idea of Sinlin but I'll put it below like this 
![image](https://user-images.githubusercontent.com/15041375/68115324-21620e00-ff33-11e9-8f4d-af545de5fd03.png)

**Comment by Jaimeloeuf** [comment]
Yea looks good, it could also be right beside the save button too! So it doesn't look so clunky.

**Comment by chaitanyapotti** [comment]
Saved done
