### ISSUE TITLE
Include ERC20 + 721 + verifiers in Tx History table

### ISSUE THREAD

**Issue by chaitanyapotti** [torusresearch/torus-website#545]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the TX history table shows only gas Used instead of Tokens/collectibles/ether sent.

**Describe the solution you'd like**
I want to see the exact tx history which shows concise amounts of tokens/collectibles/ether sent along with the gas used separately 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rathishubham7** [comment]
Do we have a UI for this ?

**Comment by chaitanyapotti** [comment]
Duplicate of #654
