### ISSUE TITLE
User Email 

### ISSUE THREAD

**Issue by chaitanyapotti** [torusresearch/torus-website#546]
**Describe the bug**
The email sent to the user needs to show the collectible info correctly.

**To Reproduce**
Make a tx using email

**Expected behavior**
Show the collectible info correctly and make necessary UX changes in the email

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version latest

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

**Additional context**
N/A

**Comment by rathishubham7** [comment]
1. PR created on torus-backend
2. Sendgrid modified

**Comment by chaitanyapotti** [comment]
Fixed
