### ISSUE TITLE
[SETTINGS] Show saved notification 

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#552]
<img width="737" alt="Screenshot 2019-11-06 at 2 20 30 PM" src="https://user-images.githubusercontent.com/53069682/68273400-3eb4ea80-00a1-11ea-959f-e12e695199e1.png">
Inform users that network change is "saved", just like the theme when "Save" is clicked.

**Comment by chaitanyapotti** [comment]
Another issue opened
