### ISSUE TITLE
[Transfer] To show "New Contact detected" notification on mobile

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#555]
![photo_2019-11-06_14-34-46](https://user-images.githubusercontent.com/53069682/68274318-c6035d80-00a3-11ea-890b-6e4821d92932.jpg)
To show "New Contact Detected" notification on mobile version. Currently it is not shown on mobile. Trying to transfer to Hagios, a new contact.

**Comment by chaitanyapotti** [comment]
Not a bug
