### ISSUE TITLE
[Transfer] Does not work

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#616]
<img width="1440" alt="Screenshot 2019-11-26 at 10 15 43 AM" src="https://user-images.githubusercontent.com/53069682/69593948-ca34f200-1035-11ea-8b7b-95961e5bf6d6.png">
Please check. 'Undefined' is shown on transfer screen for version 0.2.8

**Comment by chaitanyapotti** [comment]
Fixed
