### ISSUE TITLE
[Activity] Unsuccessful Transaction

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#617]
<img width="1030" alt="Screenshot 2019-11-26 at 10 18 00 AM" src="https://user-images.githubusercontent.com/53069682/69594075-2566e480-1036-11ea-8325-24e0ba097938.png">
UI for speed up transaction is incomplete

Please refer to below for the UI screen

<img width="375" alt="Screenshot 2019-11-26 at 10 21 45 AM" src="https://user-images.githubusercontent.com/53069682/69594213-96a69780-1036-11ea-9f01-0b5bfcad24db.png">

**Comment by chaitanyapotti** [comment]
Fixed
