### ISSUE TITLE
Unable to log into Torus Initially

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#620]
Chrome, Mac OS Desktop

The pop-up screen is stuck in this screen when trying to log in at app.tor.us

<img width="712" alt="Screenshot 2019-11-26 at 12 16 53 PM" src="https://user-images.githubusercontent.com/51352241/69599325-9d89d600-1047-11ea-8e92-a8eb9c0e937a.png">

<img width="603" alt="Screenshot 2019-11-19 at 11 25 27 AM" src="https://user-images.githubusercontent.com/51352241/69599355-b2ff0000-1047-11ea-8432-d929010dc3ea.png">

**Comment by chaitanyapotti** [comment]
Fixed the service worker issue
