### ISSUE TITLE
Transaction Hash Replacement is not updated in Activity

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#622]
For a transaction which had its transaction hashed replaced, the transaction still reflects as pending and not updated in the activity section of app.tor.us.

<img width="1260" alt="Screenshot 2019-11-26 at 12 28 42 PM" src="https://user-images.githubusercontent.com/51352241/69599545-6f58c600-1048-11ea-951a-6f746850a41a.png">

<img width="849" alt="Screenshot 2019-11-26 at 12 29 03 PM" src="https://user-images.githubusercontent.com/51352241/69599553-754ea700-1048-11ea-9fc0-77c1051c4353.png">

<img width="1259" alt="Screenshot 2019-11-26 at 12 31 24 PM" src="https://user-images.githubusercontent.com/51352241/69599627-b2b33480-1048-11ea-9029-06ee3ddedb7b.png">

**Comment by chaitanyapotti** [comment]
Not trackable
