### ISSUE TITLE
Skeleton on mobile loads as desktop

### ISSUE THREAD

**Issue by iamonuwa** [torusresearch/torus-website#628]
As a user, I want to see a skeleton properly styled and responsive for different devices.

![Screenshot_20191127-035429_Chrome](https://user-images.githubusercontent.com/6551094/69689747-0ade4b00-10ca-11ea-80cb-0240cce685f8.jpg)
![Screenshot_20191127-035821_Chrome](https://user-images.githubusercontent.com/6551094/69690099-01a1ae00-10cb-11ea-8404-6b39dbd87855.jpg)

Tested on a Google chrome browser version 78.0.3904.108 on a Samsung A70 device

**Comment by chaitanyapotti** [comment]
Done by @lionellbriones
