### ISSUE TITLE
Version v0.2.9 bug visualizing NFTs

### ISSUE THREAD

**Issue by YZhenY** [torusresearch/torus-website#635]
**Describe the bug**
NO KITTY

**To Reproduce**
1. Have kitty
2. Go to Collectibles

**Expected behavior**
I AHVE A KITTY WANT TO SEE KITTY 

**Screenshots**
![image](https://user-images.githubusercontent.com/25172440/69794124-ad024e00-1204-11ea-9fab-fa69cc7e9e81.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by chaitanyapotti** [comment]
Not a bug. Just the image didn't load from opensea (request failure). Pls reload and it would work just fine
