### ISSUE TITLE
Zooms into textboxes when entering fields in on iOS

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#645]
When trying to enter fields in the transaction screen on **Chrome**, **iOS**, the browser zooms into the textboxes, reducing the field of vision within the window, and stays that way even while navigating away to other pages.

It would help if the field of vision was maintained even when entering values as users would not require the zoom for extra clarity.

![photo_2019-12-04_16-43-49](https://user-images.githubusercontent.com/51352241/70127075-4625de80-16b5-11ea-873d-e6c7ee84dd3d.jpg)

**Comment by chaitanyapotti** [comment]
Fixed
