### ISSUE TITLE
[Transaction Summary] To show user "More details" is clickable

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#653]
<img width="301" alt="Screenshot 2019-12-10 at 4 40 07 PM" src="https://user-images.githubusercontent.com/53069682/70513009-be841800-1b6b-11ea-91ee-f25ac0589c0f.png">
Currently it shows a "I" cursor which is not intuitive to users that they can click the "More details".

Kindly make it with the hand cursor to show user its clickable when hover over "More details"
<img width="389" alt="Screenshot 2019-12-10 at 4 41 28 PM" src="https://user-images.githubusercontent.com/53069682/70513121-f3906a80-1b6b-11ea-9ecb-5151fd1390ff.png">

**Comment by chaitanyapotti** [comment]
Fixed
