### ISSUE TITLE
[Activity] ERC 721 and ERC 20 transfer is shown as send ETH 

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#654]
<img width="1142" alt="Screenshot 2019-12-10 at 4 42 53 PM" src="https://user-images.githubusercontent.com/53069682/70513233-32bebb80-1b6c-11ea-8732-963759560bf7.png">
ERC 721 transfer (I transferred a kitty) was shown as send ETH.

**Comment by itsinz** [comment]
it is supposed to show the cryptokitty 
<img width="1038" alt="Screenshot 2019-12-19 at 4 40 12 PM" src="https://user-images.githubusercontent.com/53069682/71158120-4bbb2100-227e-11ea-8123-9567ccfac4bf.png">
and you can refer it here : https://projects.invisionapp.com/d/main#/console/18774380/393810046/preview @iamonuwa

**Comment by chaitanyapotti** [comment]
Fixed
