### ISSUE TITLE
[Homepage] Is this a prank? Kicktoken

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#658]
<img width="1157" alt="Screenshot 2019-12-10 at 4 59 06 PM" src="https://user-images.githubusercontent.com/53069682/70514350-76b2c000-1b6e-11ea-9768-5b45c540d81e.png">
Is this a prank...? What is kicktoken and why does it only show up when I click refresh on the homepage? If I do not click refresh, then it does not show

**Comment by chaitanyapotti** [comment]
Not torus related
