### ISSUE TITLE
[Profile Dropdown] Remove ETH value in profile dropdown

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#659]
<img width="1298" alt="Screenshot 2019-12-10 at 5 03 17 PM" src="https://user-images.githubusercontent.com/53069682/70514837-4ddefa80-1b6f-11ea-9c14-84eb57a32d1d.png">
To remove the ETH on profile dropdown as it does not reflect the actual ETH amount users have. It is just a sum of all tokens in ETH. Keep the USD.

Change it to 
Total Value : XXX USD

**Comment by chaitanyapotti** [comment]
Done
