### ISSUE TITLE
[Homepage on iPad] Kindly align the buttons and token display

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#660]
<img width="459" alt="Screenshot 2019-12-10 at 5 28 18 PM" src="https://user-images.githubusercontent.com/53069682/70516833-a06de600-1b72-11ea-9b6b-4dc0cd34bde7.png">
Kindly align the transfer and topup button and the coins display for DAI and KNC

**Comment by chaitanyapotti** [comment]
Done by @rathishubham7
