### ISSUE TITLE
[Topup] Need to click on provider before the provider logo loads

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#666]
Provider logo does not show. It will only display AFTER selecting on the provider

<img width="479" alt="Screenshot 2019-12-13 at 6 23 26 PM" src="https://user-images.githubusercontent.com/53069682/70793156-af080780-1dd5-11ea-9812-47b4083f72b2.png">

**Comment by chaitanyapotti** [comment]
Not an issue. Some loading issues
