### ISSUE TITLE
Payment Provider Logos not loading.

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#673]
**Describe the bug**

**To Reproduce**
1. Go to to the top up page in the Torus web wallet.

**Expected behavior**
The logos of the payment providers should load together with the page.

**Screenshots**
<img width="488" alt="Screenshot 2019-12-17 at 2 22 38 PM" src="https://user-images.githubusercontent.com/51352241/70970302-f85b9e00-20d8-11ea-992f-a42bd5054a49.png">

**Desktop:**
 - OS: MacOS 10.14.16
 - Browser: Chrome

**Comment by elishatorus** [comment]
This bug is also present on Safari on MacOS.

**Desktop:**

- OS: MacOS 10.15.2 
- Browser: Safari, incognito mode

**Comment by iamonuwa** [comment]
Hey @chaitanyapotti, let me work on this. Thanks

**Comment by chaitanyapotti** [comment]
Fixed
