### ISSUE TITLE
[iOs Chrome] Change network notification did not show

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#682]
![3](https://user-images.githubusercontent.com/53069682/71164063-47e0cc00-2289-11ea-8384-f40cf3d1eb83.jpg)
Change network notification is supposed to show to notify users on the successful change of network but it does not show.

**Comment by chaitanyapotti** [comment]
We decided to show it only for rpc save. Not for all network changes.
But, @itsinz please let us know if you want it for all

**Comment by chaitanyapotti** [comment]
Fixed
