### ISSUE TITLE
Bad MAC issue

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#687]
**Describe the bug**
Page stuck when logging in with Twitch

**To Reproduce**
1. Go to 'testing.tor.us'
2. Log in with Twitch
3. The page is stuck

**Expected behavior**
Expected the page to load to the wallet page.

**Screenshots**
<img width="1792" alt="Screenshot 2019-12-20 at 11 23 41 AM" src="https://user-images.githubusercontent.com/51352241/71227860-7c04cd00-231b-11ea-8d38-fc5c5886f12c.png">

**Desktop (please complete the following information):**
 - OS 10.15.2
 - Browser: Safari

**Comment by elishatorus** [comment]
The error was present in the first time login for the account.

**Comment by elishatorus** [comment]
Same error occurs when logging in with Google on a new account.

**Comment by chaitanyapotti** [comment]
Fixed
