### ISSUE TITLE
[iOS Chrome] Unable to send via scanning QR Code

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#690]
![998](https://user-images.githubusercontent.com/53069682/71233345-4fa77b80-2330-11ea-9ed1-ed33fc8c264d.jpg)
![999](https://user-images.githubusercontent.com/53069682/71233346-50401200-2330-11ea-9955-eaadee22f271.jpg)

In torus transaction screen, unable to scan and get eth addresses of user's QR Code.

**Comment by chaitanyapotti** [comment]
Not a bug
