### ISSUE TITLE
[iOS Safari] Unable to conduct transactions after scanning QR code.

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#691]
**Describe the bug**
Unable to conduct transactions from Safari iOS after scanning QR code, the page is frozen in place.

**To Reproduce**
Steps to reproduce the behaviour:
1. Scan Torus QR code on the phone, it opens up within the phone's browser, log in.
2. Attempt to conduct a transaction.
3. Nothing happens after the Transfer button is clicked, the transaction is unable to be processed.

**Expected behaviour**
The pop-up confirming the transaction should appear.

**Screenshots**
![photo_2019-12-20_14-10-53](https://user-images.githubusercontent.com/51352241/71234067-91392600-2332-11ea-902b-0d29f49d2fe7.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.3
 - Browser: Safari

**Comment by chaitanyapotti** [comment]
Not a bug
