### ISSUE TITLE
[iOS Chrome] Unable to login wallet from "Send tokens to a new Google account, and log into the wallet from the email notification"

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#692]
![1111](https://user-images.githubusercontent.com/53069682/71235473-453cb000-2337-11ea-9f4f-84439b6d34c0.jpg)

Stuck at skeleton placeholder when trying to login for "Send tokens to a new Google account, and log into the wallet from the email notification"

When refresh, goes back to login page

**Comment by chaitanyapotti** [comment]
Fixed
