### ISSUE TITLE
[Firefox] I cannot save the new address as contact

### ISSUE THREAD

**Issue by carloslastresDev** [torusresearch/torus-website#696]
**Describe the bug**
I cannot save the new address as contact

**To Reproduce**
1. Go to Transfer
2. Copy a new ETH address but do not select "Transfer mode"

![image](https://user-images.githubusercontent.com/15041375/71307322-a348c080-2427-11ea-96d3-4b31f788b96b.png)

3. Click "save contact"
4. The action cannot be performed and there's a weird light blue circle

![image](https://user-images.githubusercontent.com/15041375/71307332-b8bdea80-2427-11ea-9357-26b0397d0d8f.png)

**Expected behavior**
1) Should autodetect that is ETH address
2) Should allow the user to save the contact 
3) Should indicate the user about selecting a method

 - Macbook
 - FIrefox

**Comment by chaitanyapotti** [comment]
Fixed
