### ISSUE TITLE
Unable to Transfer ETH to new Reddit Username saved in Address Book

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#705]
**Describe the bug**
Unable to perform new transactions to new Reddit username that was just saved in the Address Book.

**To Reproduce**
1. Go to the transfer page.
2. Enter new Reddit username to transfer funds to.
3. Add contact to Address book.
4. Click Transfer.
5. The page is stuck and does not load.

**Expected behavior**
The transfer process should continue after the button is pressed.

**Screenshots**
<img width="1792" alt="Screenshot 2019-12-26 at 11 26 31 AM" src="https://user-images.githubusercontent.com/51352241/71500372-af0d0a80-289f-11ea-9397-192aebc0eda6.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by chaitanyapotti** [comment]
Fixed
