### ISSUE TITLE
Activity Page transactions are not accurate representations of the transactions

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#706]
**Describe the bug**
Transactions in the activity page show up as unsuccessful, despite it being successful on Etherscan.
This occurs in some of the transactions conducted.

**To Reproduce**
1. Conduct a transfer.
2. Go to the activity page.

**Expected behavior**
The state of the transactions should reflect what is shown on etherscan.

**Screenshots**
![Screenshot 2019-12-25 at 1 21 30 AM](https://user-images.githubusercontent.com/51352241/71500562-7883bf80-28a0-11ea-81ea-4987c1e20d99.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by chaitanyapotti** [comment]
Fixed
