### ISSUE TITLE
[Activity] Takes 2 seconds to load. Place a loader rather than "No data available"

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#709]
<img width="1440" alt="Screenshot 2020-01-02 at 3 32 35 PM" src="https://user-images.githubusercontent.com/53069682/71656480-54c7ea00-2d76-11ea-92d9-a47a1768c7bf.png">
To put a loader instead of "No Data Available" for activity page because it takes at least 2 seconds to load.

**Comment by chaitanyapotti** [comment]
Please use the `loading` slot to define the loader
https://vuetifyjs.com/en/components/data-iterators
