### ISSUE TITLE
[Activity] Period filter does not work

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#710]
<img width="1157" alt="Screenshot 2020-01-02 at 4 07 39 PM" src="https://user-images.githubusercontent.com/53069682/71657281-24824a80-2d7a-11ea-99c9-1f224bb6e8e6.png">
Type of transaction filter works.
Period filter does not work.

Also, the following situation render the filter fully not functional :
Step 1 : Filter according to type of transaction (Works)
Step 2 : Filter according to Period (Does not work)
Step 3 : Filter according to type of transaction again (Does not work now)

**Comment by chaitanyapotti** [comment]
Fixed
