### ISSUE TITLE
[Transfer] Chrome auto fill still shows on Transfer page

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#712]
<img width="319" alt="Screenshot 2020-01-02 at 5 06 45 PM" src="https://user-images.githubusercontent.com/53069682/71659394-63b49980-2d82-11ea-81cb-70f13c1958b4.png">
Chrome auto fill still shows on transfer page despite first fix

**Comment by chaitanyapotti** [comment]
Please check again
