### ISSUE TITLE
Torus Wallet does not fully reflect all NFTs associated with my wallet

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#734]
**Describe the bug**
Torus Wallet does not fully reflect all NFTs associated with my wallet. I can only view all my NFTs in OpenSea.

**To Reproduce**
1. Log in at https://app.tor.us
2. Go to Home
3. Go to Collectibles

**Expected behavior**
I should be able to view all my NFTs within the Torus wallet.

**Screenshots**
<img width="1167" alt="Screenshot 2020-01-09 at 5 09 03 PM" src="https://user-images.githubusercontent.com/51352241/72055003-03cf6d00-3305-11ea-8dfc-b866379bf8a0.png">
NFTs in Torus does not match NFTs in OpenSea.
<img width="936" alt="Screenshot 2020-01-09 at 5 09 32 PM" src="https://user-images.githubusercontent.com/51352241/72055004-03cf6d00-3305-11ea-9daf-ddaa0cf6efd0.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome

**Comment by chaitanyapotti** [comment]
Fixed
