### ISSUE TITLE
[Activity] Receive token but there is nothing on activity page

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#736]
<img width="1394" alt="Screenshot 2020-01-09 at 6 30 51 PM" src="https://user-images.githubusercontent.com/53069682/72060130-5a8d7480-330e-11ea-8923-6a4938e4535b.png">
Activity not working when I receive token.
Also, please fix the part where the line of the navigation is located

**Comment by chaitanyapotti** [comment]
Fixed in #753
