### ISSUE TITLE
[Activity] Error with Translation for Mandarin and Korean

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#737]
![photo_2020-01-09_18-34-36](https://user-images.githubusercontent.com/51191261/72060372-cd96eb00-330e-11ea-853e-9d0ea81e5186.jpg)
![photo_2020-01-09_18-34-35](https://user-images.githubusercontent.com/51191261/72060374-cd96eb00-330e-11ea-8b91-d3ad98c47ce2.jpg)
Languages are reversed for Mandarin and Korean for "Sent"

**Comment by lionellbriones** [comment]
Fixed on airtable
