### ISSUE TITLE
[Transaction Activities] Transaction disappears after refreshing

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#742]
* Android Chrome
Made a transfer to newly added contact.
Showed as pending but activity disappears after refreshing although the transaction has gone through.
Payee's activity page also stays blank although the money is in the wallet.
![image](https://user-images.githubusercontent.com/51191261/72062901-a8f14200-3313-11ea-9587-4f658a827cdc.png)
![image](https://user-images.githubusercontent.com/51191261/72063055-fb326300-3313-11ea-8460-ff4739fdba12.png)
<img width="1440" alt="Screenshot 2020-01-09 at 7 13 56 PM" src="https://user-images.githubusercontent.com/51191261/72063146-316fe280-3314-11ea-92d3-46c69eceac21.png">

**Comment by hagiosssss** [comment]
This happens for older contacts as well
![Error](https://user-images.githubusercontent.com/51191261/72123541-9111d080-339c-11ea-832f-a4687e739a81.png)

**Comment by hagiosssss** [comment]
![Discord 2020-01-10 13_14_42](https://user-images.githubusercontent.com/51191261/72127618-392e9600-33ab-11ea-8047-5c61612a7f47.gif)
Transaction history disappears after refreshing (happens for Discord, Reddit as well)

**Comment by hagiosssss** [comment]
Occurs for ERC20 as well 
![ERC20](https://user-images.githubusercontent.com/51191261/72129857-b3164d80-33b2-11ea-940e-868712d3fcf1.gif)

**Comment by chaitanyapotti** [comment]
Fixed in #753
