### ISSUE TITLE
[Activity] transfer erc 721 but activity page shows ETH and also not the token image

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#744]
<img width="1139" alt="Screenshot 2020-01-09 at 7 43 22 PM" src="https://user-images.githubusercontent.com/53069682/72065109-5e25f900-3318-11ea-9897-cd855d154f6b.png">

**Comment by hagiosssss** [comment]
Same for Android Chrome

**Comment by chaitanyapotti** [comment]
Fixed in #753
