### ISSUE TITLE
[Transfer ERC 721] Transferred to a smart contract wallet instead (!!!)

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#745]
<img width="409" alt="Screenshot 2020-01-09 at 7 46 47 PM" src="https://user-images.githubusercontent.com/53069682/72065319-eb694d80-3318-11ea-9ed6-2dd5db845fdb.png">
Sent to : 0x63A2D8eE8A1B5Bb842D4c0dFDDED6ae5207F8E94 
BUT in the activity page and etherscan it was sent to a smart contract wallet : 0x0e3a2a1f2146d86a604adc220b4967a898d7fe07

Transaction detail here : https://etherscan.io/tx/0x00a0a6713e51670cc4b600cae119472eec7aa2c3f178148aefc212d4a1a211ab

**Comment by chaitanyapotti** [comment]
It shows the contract you sent to (The asset belongs to that contract).
We are doing a minor revamp to change this.

**Comment by chaitanyapotti** [comment]
Fixed in #753
