### ISSUE TITLE
[Sending ERC 721] Two transactions on the same ERC 721, both transaction disappear from activity page

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#759]
![image](https://user-images.githubusercontent.com/53069682/72246458-b8330100-362d-11ea-9d84-5f5c3033f947.png)
![image](https://user-images.githubusercontent.com/53069682/72246465-bd904b80-362d-11ea-8f37-4d8ab1f738cb.png)

Situation 
1. Transferred ERC 721 Item A to ETH Address 
2. Transferring ERC 721 Item A to Discord ID -> Surprised that wallet still has that ERC 721 and a transaction was sent.
3. Transaction loaded on activity page. upon refreshing, transaction 1 and 2 both disappeared from the activity page. hence the screenshot above was what I see after completing both transaction 1&2

**Comment by chaitanyapotti** [comment]
No bug
