### ISSUE TITLE
[Android Chrome] Disappearing Transaction Activity

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#764]
**On Android Chrome**
Activity: Sending ETH & ERC
Problem: Transactions made on Android Chrome disappears after refreshing the page (transaction goes through but doesn't show on either devices/accounts)
![ERC20](https://user-images.githubusercontent.com/51191261/72517504-7a80e300-388e-11ea-84aa-922001ec3baf.gif)

**Comment by chaitanyapotti** [comment]
Fixed
