### ISSUE TITLE
[Transfer] Auto-fill to auto load address book with a match upon typing

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#765]
<img width="608" alt="Screenshot 2020-01-16 at 6 32 51 PM" src="https://user-images.githubusercontent.com/53069682/72517651-ba47ca80-388e-11ea-81ef-975705620576.png">
Right now the auto load of address does not work upon typing. 
It should load and filter the addreess book based on the text typed

**Comment by chaitanyapotti** [comment]
Please don't use `:return-object="true"` on the vue-component
