### ISSUE TITLE
[Activity] ERC 20 make it circle

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#767]
<img width="1158" alt="Screenshot 2020-01-16 at 6 53 27 PM" src="https://user-images.githubusercontent.com/53069682/72519047-93d75e80-3891-11ea-9a0d-8d955d99fbb0.png">
Please make ERC 20 circle. It is square in dark mode for Augur.

**Comment by chaitanyapotti** [comment]
Can't i think.! it would crop their logo which would violate t&c.
They only provide jpg i think.!
