### ISSUE TITLE
[Simplex Topup] unable to work on simplex

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#768]
<img width="1199" alt="Screenshot 2020-01-16 at 6 59 34 PM" src="https://user-images.githubusercontent.com/53069682/72520044-8e7b1380-3893-11ea-82f9-1afdcc9743df.png">
Simplex top up does not work. It says to unblock pop up but i am unable to do it. Moonpay works. 

This is on safari.

**Comment by chaitanyapotti** [comment]
Fixed
