### ISSUE TITLE
[Safari Browser] Misalignment for Display of Currencies

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#806]
Dropdown does not display the currencies in full
<img width="1440" alt="Screenshot 2020-02-05 at 5 10 58 PM" src="https://user-images.githubusercontent.com/51191261/73827515-a7476b00-483a-11ea-82c6-a1c95d3a5a7a.png">

**Comment by lionellbriones** [comment]
Removed custom scroll bar for now - causing issue on safari
