### ISSUE TITLE
[iOS Chrome] It is not dark mode everywhere, loading not centralised

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#810]
1. Loading is also not centralised
![photo_2020-02-05_17-56-25](https://user-images.githubusercontent.com/53069682/73831193-dd87e900-4840-11ea-8589-34355f0971e3.jpg)

**Comment by chaitanyapotti** [comment]
@lionellbriones pls check if dark mode is enabled in RedirectCatch.vue
Only chrome on Ios has this issue.

**Comment by lionellbriones** [comment]
> @lionellbriones pls check if dark mode is enabled in RedirectCatch.vue
> Only chrome on Ios has this issue.

yes, dark mode is enabled on RedirectCatch

**Comment by chaitanyapotti** [comment]
Too Specific. Will do later
