### ISSUE TITLE
Show Encryption when user is trying to export private key json file

### ISSUE THREAD

**Issue by elishatorus** [torusresearch/torus-website#826]
**Describe the improvement**
When the user is trying to export the private key through json file, after they key in their password, we should show the encrypting process, to let the users know that the file is being encrypted and that there is another step to click to download the file. Perhaps display the greyed out download button until the file is encrypted.

**To Reproduce**
Export the private key through json file.

<img width="1792" alt="Screenshot 2020-02-06 at 3 07 18 PM" src="https://user-images.githubusercontent.com/51352241/73914947-3d3fcc00-48f5-11ea-9061-89ad4bc5532f.png">

**Comment by itsinz** [comment]
<img width="453" alt="Screenshot 2020-02-06 at 3 46 47 PM" src="https://user-images.githubusercontent.com/53069682/73916186-e982b200-48f7-11ea-9801-a4adf5ab1c8d.png">
Circle to indicate loader at the left side
