### ISSUE TITLE
[Wallet Homepage] Show as 0.00 ETH instead of 6.55e-15 ETH

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#834]
![photo_2020-02-07_16-34-34](https://user-images.githubusercontent.com/53069682/74013645-ef47c880-49c7-11ea-9cc3-f2ed7fe1dd7e.jpg)
User transferred all ETH out of wallet but was shown this on iOS Chrome homepage.
Please take care that when send all ETH out of wallet, 0 ETH is left not 6.55e-15 ETH.

**Comment by chaitanyapotti** [comment]
This is fine for now.
