### ISSUE TITLE
[Transaction Summary] Make number more friendly

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#853]
<img width="1440" alt="Screenshot 2020-02-14 at 11 35 08 AM" src="https://user-images.githubusercontent.com/53069682/74505172-6c77be00-4f31-11ea-94e3-5b5f0f530cc1.png">
Format the e+59 to 10^59. The same for e-19 to e^-19.

**Comment by rathishubham7** [comment]
This is the expected behavior. Same as metamask

**Comment by chaitanyapotti** [comment]
Closing this
