### ISSUE TITLE
[On Totle] Metamask is displayed instead of Torus wallet

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#854]
<img width="1440" alt="Screenshot 2020-02-14 at 11 35 42 AM" src="https://user-images.githubusercontent.com/53069682/74505269-afd22c80-4f31-11ea-9017-04c1fe3ef9d0.png">
Situation : 
Signed in via torus but on the profile it shows Metamask Wallet instead of Torus wallet.

**Comment by tetratorus** [comment]
This isn't an issue with our wallet, our wallet emulates Metamask's provider to provide 100% compatibility with existing dapps that already work with Metamask. This includes a flag called isMetamask.

however, sites can check if isTorus is set to true to determine if it's a Torus wallet.
