### ISSUE TITLE
[Transaction Activity Page] Sign message gets display as a 'transaction' on activity page

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#856]
<img width="425" alt="Screenshot 2020-02-14 at 3 55 17 PM" src="https://user-images.githubusercontent.com/53069682/74512070-6b9b5800-4f42-11ea-94d5-727f67400871.png">
<img width="1121" alt="Screenshot 2020-02-14 at 3 52 58 PM" src="https://user-images.githubusercontent.com/53069682/74512072-6dfdb200-4f42-11ea-8e89-fe6ce3c9359b.png">
Sign message gets displayed as a 'transaction' on activity.

This is the transaction details on etherscan : https://etherscan.io/tx/0xedce104c2641ff5c8328c92cab9fdf8e1009a57fa93159bd5888e88027511f29

This should be under permissions where users get to see who and how much they have approve to spend.

**Comment by rathishubham7** [comment]
This will be implemented along with the permissions

**Comment by chaitanyapotti** [comment]
Closing for now
