### ISSUE TITLE
[torque] Torus widget loads in the center of the screen. The screens freezes in loading

### ISSUE THREAD

**Issue by carloslastresDev** [torusresearch/torus-website#857]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15041375/74518205-59bfb200-4f4e-11ea-8bd9-14e61b5c1b7e.png)

**To Reproduce**
1. Go to https://torque.loans/
2. Login with Torus
3. See error

**Expected behavior**
Torus above the intercom widget and completed loading

**Desktop (please complete the following information):**
 - OS
 - Chrome

**Comment by chaitanyapotti** [comment]
Issue with torque. Not us
@elishatorus pls open a channel of discussion with them
