### ISSUE TITLE
[Multiple language] Change copywriting to Language changed to (respective language)

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#879]
<img width="312" alt="Screenshot 2020-02-27 at 6 11 23 PM" src="https://user-images.githubusercontent.com/53069682/75434538-ab276280-598c-11ea-8e74-199e0594b3c2.png">
Change copy writing to "Language changed to (whatever selected by user)"

**Comment by cheran-senthil** [comment]
Perhaps that should be in the new language too, instead of English.

**Comment by itsinz** [comment]
> Perhaps that should be in the new language too, instead of English.

Makes sense. Will update locales airtable

**Comment by chaitanyapotti** [comment]
Closed in https://github.com/torusresearch/torus-website/pull/896
