### ISSUE TITLE
[Snack Bar] Improve copywriting

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#880]
<img width="1440" alt="Screenshot 2020-02-27 at 6 15 39 PM" src="https://user-images.githubusercontent.com/53069682/75435026-64863800-598d-11ea-8324-596536155478.png">
Change "successfully updated theme" to "Theme updated"
Please capitalise the first letter of the line. line.capitliaze()

**Comment by lionellbriones** [comment]
Will move snackbar messages on airtable

**Comment by chaitanyapotti** [comment]
Closed in https://github.com/torusresearch/torus-website/pull/896
