### ISSUE TITLE
[Transaction] Untidy number display when transfer by USD to ETH Address

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#884]
<img width="1163" alt="Screenshot 2020-02-27 at 6 45 20 PM" src="https://user-images.githubusercontent.com/53069682/75437660-8e415e00-5991-11ea-8b87-8ca48619ff23.png">
Please tidy up the number when transfer by USD. 
Tidy up all small numbers. 
It can be less than 0.00000 USD.

**Comment by iamonuwa** [comment]
Let's round it off to 2 decimal places. 0.00? @itsinz wdyt?

**Comment by itsinz** [comment]
alternatively we can make use of the gwei unit instead and providie hover over tool tip for unit conversion. this way we can keep it to 2 dp + use gwei units. might be more tidy. what are your thoughts?

**Comment by iamonuwa** [comment]
Tooltip to show the actual value sounds great. Can make it 0.00000 and still show the tooltip.
