### ISSUE TITLE
[Settings] Make the network notification to the snack bar

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#888]
<img width="754" alt="Screenshot 2020-02-27 at 7 20 52 PM" src="https://user-images.githubusercontent.com/53069682/75440268-6dc7d280-5996-11ea-9eb6-12568cd90103.png">
Please make the network change notification into snack bar at the top, just like the theme change and contact list.

**Comment by chaitanyapotti** [comment]
Closed in https://github.com/torusresearch/torus-website/pull/896
