### ISSUE TITLE
[Activity] Change global currency but activity page currency still in usd

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#905]
<img width="138" alt="Screenshot 2020-02-28 at 5 23 51 PM" src="https://user-images.githubusercontent.com/53069682/75532128-3701c300-5a4f-11ea-81fb-fff792acd672.png">
Changed currency on homepage to SGD but activity currency is still USD.
Make it sync with sgd

**Comment by chaitanyapotti** [comment]
This is intended
