### ISSUE TITLE
Double toggle "ETH" shown in Transfer Page

### ISSUE THREAD

**Issue by carloslastresDev** [torusresearch/torus-website#911]
**Describe the bug**
If your default currency is ETH, once you go to transfer, you will have 2 "ETH" on the field "You Send"

![image](https://user-images.githubusercontent.com/15041375/75606255-e9a45500-5b25-11ea-8419-e3a39643822f.png)

**To Reproduce**
1. Select ETH currency as the default
2. Go to transfer page and check the field "You Send"

**Expected behavior**
In this case, should be USD & ETH as well

**Desktop (please complete the following information):**
 - Chrome, Macbook

**Comment by chaitanyapotti** [comment]
Showing only one of them if both are ETH.!
