### ISSUE TITLE
Phone sign up gets autofilled with email and password

### ISSUE THREAD

**Issue by carloslastresDev** [torusresearch/torus-website#917]
**Describe the bug**
Once I try to sign up with the phone, I get my email auto-filled in the phone field and I get my password filled as well

**To Reproduce**
1. Go to https://alpha.tor.us/
2. Click on login with phone
3. Click on Sign up
![image](https://user-images.githubusercontent.com/15041375/75759232-324f4e80-5d70-11ea-8267-89f789e979bf.png)

**Expected behavior**
Shouldn't auto-fill and should only allow you to put numbers

**Screenshots**

![image](https://user-images.githubusercontent.com/15041375/75759384-6dea1880-5d70-11ea-9236-dd56577af01a.png)

Also, doesn't verify it's a real number

![image](https://user-images.githubusercontent.com/15041375/75759423-84906f80-5d70-11ea-9e30-730a49806a22.png)

Tested in Macbook

**Comment by chaitanyapotti** [comment]
Fixed this already
