### ISSUE TITLE
Not receiving SMS for login

### ISSUE THREAD

**Issue by carloslastresDev** [torusresearch/torus-website#918]
**Describe the bug**

**To Reproduce**
1. Go to 'https://alpha.tor.us/torus-phone-register
2. Fill your information and add a real number from any other country
3. Code never arrives

**Comment by chaitanyapotti** [comment]
@cheran-senthil @tetratorus pls look into this. i don't have access to twilio dashboard

**Comment by tetratorus** [comment]
fixed
