### ISSUE TITLE
[Activity] Top up transaction does not show

### ISSUE THREAD

**Issue by itsinz** [torusresearch/torus-website#920]
<img width="1163" alt="Screenshot 2020-03-06 at 3 23 51 PM" src="https://user-images.githubusercontent.com/53069682/76061539-b434b700-5fbe-11ea-9b17-5b19a8c72849.png">
Topped up with moonpay but activity does not show

Transaction hash : 0x62b7f5f6f3430796585f46aa0556960a60f33a8b3b318e3ea2b3ab6f2e98fd84

**Comment by rathishubham7** [comment]
Resolved. We removed the validations from the API and modified the schema. This should be fixed now.

**Comment by itsinz** [comment]
this is not fix on testing.tor.us. please check again thanks

**Comment by chaitanyapotti** [comment]
Now it shows.! Fixed
