### ISSUE TITLE
[Import Account] Translation under Import Type does not change accordingly 

### ISSUE THREAD

**Issue by hagiosssss** [torusresearch/torus-website#929]
Dropdown under 'Import Type' remains in the initial language and does not change

For eg, wallet was initially in English, after changing to Japanese, the dropdown still remains in English.
![image](https://user-images.githubusercontent.com/51191261/76677548-837dfe80-660a-11ea-9fd0-a76781176058.png)
![image](https://user-images.githubusercontent.com/51191261/76677521-3dc13600-660a-11ea-9bb5-ecb32e433cd5.png)
![image](https://user-images.githubusercontent.com/51191261/76677524-40bc2680-660a-11ea-9049-c3a99dd55add.png)

**Comment by chaitanyapotti** [comment]
Fixed
