### ISSUE TITLE
TRS-01-007 Server: Error messages leaked via sockjs (Info) 

### ISSUE THREAD

**Issue by chaitanyapotti** [torusresearch/torus-website#95]
When the Torus script is injected into a web page, a WebSocket connection will be established via sockjs. While observing the related traffic, it was found that error messages are leaked in the response.
Sample leakage: a["{\"type\":\"warnings\",\"data\":[\"./node_modules/ethereumjs-vm/dist/ runJit.js 13:16-23\\nCritical dependency: require function is used in a way in which dependencies cannot be statically extracted\"]}"]
Upon further investigation, this seems to be a dependency of webpack-dev-server and hence should not affect the production server if configured correctly.

**Comment by tetratorus** [comment]
fixed in production. this is only an issue when using npm run serve in local
